/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq;


import com.zwstudio.lolly.jooq.tables.Autocorrect;
import com.zwstudio.lolly.jooq.tables.Dictionaries;
import com.zwstudio.lolly.jooq.tables.Dicttypes;
import com.zwstudio.lolly.jooq.tables.Etextbooks;
import com.zwstudio.lolly.jooq.tables.Langphrases;
import com.zwstudio.lolly.jooq.tables.Languages;
import com.zwstudio.lolly.jooq.tables.Langwords;
import com.zwstudio.lolly.jooq.tables.Sites;
import com.zwstudio.lolly.jooq.tables.Textbooks;
import com.zwstudio.lolly.jooq.tables.Textsites;
import com.zwstudio.lolly.jooq.tables.Unitphrases;
import com.zwstudio.lolly.jooq.tables.Unitwords;
import com.zwstudio.lolly.jooq.tables.Users;
import com.zwstudio.lolly.jooq.tables.Usersettings;
import com.zwstudio.lolly.jooq.tables.Vdictionaries;
import com.zwstudio.lolly.jooq.tables.Vetextbooks;
import com.zwstudio.lolly.jooq.tables.Vlanguages;
import com.zwstudio.lolly.jooq.tables.Vtextbooks;
import com.zwstudio.lolly.jooq.tables.Vtextbookwords;
import com.zwstudio.lolly.jooq.tables.Vtextsites;
import com.zwstudio.lolly.jooq.tables.Vunitphrases;
import com.zwstudio.lolly.jooq.tables.Vusersettings;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 2000038992;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>AUTOCORRECT</code>.
     */
    public final Autocorrect AUTOCORRECT = com.zwstudio.lolly.jooq.tables.Autocorrect.AUTOCORRECT;

    /**
     * The table <code>DICTIONARIES</code>.
     */
    public final Dictionaries DICTIONARIES = com.zwstudio.lolly.jooq.tables.Dictionaries.DICTIONARIES;

    /**
     * The table <code>DICTTYPES</code>.
     */
    public final Dicttypes DICTTYPES = com.zwstudio.lolly.jooq.tables.Dicttypes.DICTTYPES;

    /**
     * The table <code>ETEXTBOOKS</code>.
     */
    public final Etextbooks ETEXTBOOKS = com.zwstudio.lolly.jooq.tables.Etextbooks.ETEXTBOOKS;

    /**
     * The table <code>LANGPHRASES</code>.
     */
    public final Langphrases LANGPHRASES = com.zwstudio.lolly.jooq.tables.Langphrases.LANGPHRASES;

    /**
     * The table <code>LANGUAGES</code>.
     */
    public final Languages LANGUAGES = com.zwstudio.lolly.jooq.tables.Languages.LANGUAGES;

    /**
     * The table <code>LANGWORDS</code>.
     */
    public final Langwords LANGWORDS = com.zwstudio.lolly.jooq.tables.Langwords.LANGWORDS;

    /**
     * The table <code>SITES</code>.
     */
    public final Sites SITES = com.zwstudio.lolly.jooq.tables.Sites.SITES;

    /**
     * The table <code>TEXTBOOKS</code>.
     */
    public final Textbooks TEXTBOOKS = com.zwstudio.lolly.jooq.tables.Textbooks.TEXTBOOKS;

    /**
     * The table <code>TEXTSITES</code>.
     */
    public final Textsites TEXTSITES = com.zwstudio.lolly.jooq.tables.Textsites.TEXTSITES;

    /**
     * The table <code>UNITPHRASES</code>.
     */
    public final Unitphrases UNITPHRASES = com.zwstudio.lolly.jooq.tables.Unitphrases.UNITPHRASES;

    /**
     * The table <code>UNITWORDS</code>.
     */
    public final Unitwords UNITWORDS = com.zwstudio.lolly.jooq.tables.Unitwords.UNITWORDS;

    /**
     * The table <code>USERS</code>.
     */
    public final Users USERS = com.zwstudio.lolly.jooq.tables.Users.USERS;

    /**
     * The table <code>USERSETTINGS</code>.
     */
    public final Usersettings USERSETTINGS = com.zwstudio.lolly.jooq.tables.Usersettings.USERSETTINGS;

    /**
     * The table <code>VDICTIONARIES</code>.
     */
    public final Vdictionaries VDICTIONARIES = com.zwstudio.lolly.jooq.tables.Vdictionaries.VDICTIONARIES;

    /**
     * The table <code>VETEXTBOOKS</code>.
     */
    public final Vetextbooks VETEXTBOOKS = com.zwstudio.lolly.jooq.tables.Vetextbooks.VETEXTBOOKS;

    /**
     * The table <code>VLANGUAGES</code>.
     */
    public final Vlanguages VLANGUAGES = com.zwstudio.lolly.jooq.tables.Vlanguages.VLANGUAGES;

    /**
     * The table <code>VTEXTBOOKS</code>.
     */
    public final Vtextbooks VTEXTBOOKS = com.zwstudio.lolly.jooq.tables.Vtextbooks.VTEXTBOOKS;

    /**
     * The table <code>VTEXTBOOKWORDS</code>.
     */
    public final Vtextbookwords VTEXTBOOKWORDS = com.zwstudio.lolly.jooq.tables.Vtextbookwords.VTEXTBOOKWORDS;

    /**
     * The table <code>VTEXTSITES</code>.
     */
    public final Vtextsites VTEXTSITES = com.zwstudio.lolly.jooq.tables.Vtextsites.VTEXTSITES;

    /**
     * The table <code>VUNITPHRASES</code>.
     */
    public final Vunitphrases VUNITPHRASES = com.zwstudio.lolly.jooq.tables.Vunitphrases.VUNITPHRASES;

    /**
     * The table <code>VUSERSETTINGS</code>.
     */
    public final Vusersettings VUSERSETTINGS = com.zwstudio.lolly.jooq.tables.Vusersettings.VUSERSETTINGS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Autocorrect.AUTOCORRECT,
            Dictionaries.DICTIONARIES,
            Dicttypes.DICTTYPES,
            Etextbooks.ETEXTBOOKS,
            Langphrases.LANGPHRASES,
            Languages.LANGUAGES,
            Langwords.LANGWORDS,
            Sites.SITES,
            Textbooks.TEXTBOOKS,
            Textsites.TEXTSITES,
            Unitphrases.UNITPHRASES,
            Unitwords.UNITWORDS,
            Users.USERS,
            Usersettings.USERSETTINGS,
            Vdictionaries.VDICTIONARIES,
            Vetextbooks.VETEXTBOOKS,
            Vlanguages.VLANGUAGES,
            Vtextbooks.VTEXTBOOKS,
            Vtextbookwords.VTEXTBOOKWORDS,
            Vtextsites.VTEXTSITES,
            Vunitphrases.VUNITPHRASES,
            Vusersettings.VUSERSETTINGS);
    }
}
