/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq;


import com.zwstudio.lolly.jooq.tables.Autocorrect;
import com.zwstudio.lolly.jooq.tables.Dictionaries;
import com.zwstudio.lolly.jooq.tables.Dicttypes;
import com.zwstudio.lolly.jooq.tables.Etextbooks;
import com.zwstudio.lolly.jooq.tables.Langphrases;
import com.zwstudio.lolly.jooq.tables.Languages;
import com.zwstudio.lolly.jooq.tables.Langwords;
import com.zwstudio.lolly.jooq.tables.Sites;
import com.zwstudio.lolly.jooq.tables.Textbooks;
import com.zwstudio.lolly.jooq.tables.Textsites;
import com.zwstudio.lolly.jooq.tables.Unitphrases;
import com.zwstudio.lolly.jooq.tables.Unitwords;
import com.zwstudio.lolly.jooq.tables.Users;
import com.zwstudio.lolly.jooq.tables.Usersettings;
import com.zwstudio.lolly.jooq.tables.records.AutocorrectRecord;
import com.zwstudio.lolly.jooq.tables.records.DictionariesRecord;
import com.zwstudio.lolly.jooq.tables.records.DicttypesRecord;
import com.zwstudio.lolly.jooq.tables.records.EtextbooksRecord;
import com.zwstudio.lolly.jooq.tables.records.LangphrasesRecord;
import com.zwstudio.lolly.jooq.tables.records.LanguagesRecord;
import com.zwstudio.lolly.jooq.tables.records.LangwordsRecord;
import com.zwstudio.lolly.jooq.tables.records.SitesRecord;
import com.zwstudio.lolly.jooq.tables.records.TextbooksRecord;
import com.zwstudio.lolly.jooq.tables.records.TextsitesRecord;
import com.zwstudio.lolly.jooq.tables.records.UnitphrasesRecord;
import com.zwstudio.lolly.jooq.tables.records.UnitwordsRecord;
import com.zwstudio.lolly.jooq.tables.records.UsersRecord;
import com.zwstudio.lolly.jooq.tables.records.UsersettingsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AutocorrectRecord> PK_AUTOCORRECT = UniqueKeys0.PK_AUTOCORRECT;
    public static final UniqueKey<DictionariesRecord> PK_DICTIONARIES = UniqueKeys0.PK_DICTIONARIES;
    public static final UniqueKey<DicttypesRecord> PK_DICTTYPES = UniqueKeys0.PK_DICTTYPES;
    public static final UniqueKey<EtextbooksRecord> PK_ETEXTBOOKS = UniqueKeys0.PK_ETEXTBOOKS;
    public static final UniqueKey<LangphrasesRecord> PK_LANGPHRASES = UniqueKeys0.PK_LANGPHRASES;
    public static final UniqueKey<LanguagesRecord> PK_LANGUAGES = UniqueKeys0.PK_LANGUAGES;
    public static final UniqueKey<LangwordsRecord> PK_LANGWORDS = UniqueKeys0.PK_LANGWORDS;
    public static final UniqueKey<SitesRecord> PK_SITES = UniqueKeys0.PK_SITES;
    public static final UniqueKey<TextbooksRecord> PK_TEXTBOOKS = UniqueKeys0.PK_TEXTBOOKS;
    public static final UniqueKey<TextsitesRecord> PK_TEXTSITES = UniqueKeys0.PK_TEXTSITES;
    public static final UniqueKey<UnitphrasesRecord> PK_UNITPHRASES = UniqueKeys0.PK_UNITPHRASES;
    public static final UniqueKey<UnitwordsRecord> PK_UNITWORDS = UniqueKeys0.PK_UNITWORDS;
    public static final UniqueKey<UsersRecord> PK_USERS = UniqueKeys0.PK_USERS;
    public static final UniqueKey<UsersettingsRecord> PK_USERSETTINGS = UniqueKeys0.PK_USERSETTINGS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AutocorrectRecord, LanguagesRecord> FK_AUTOCORRECT_LANGUAGES_1 = ForeignKeys0.FK_AUTOCORRECT_LANGUAGES_1;
    public static final ForeignKey<DictionariesRecord, LanguagesRecord> FK_DICTIONARIES_LANGUAGES_2 = ForeignKeys0.FK_DICTIONARIES_LANGUAGES_2;
    public static final ForeignKey<DictionariesRecord, LanguagesRecord> FK_DICTIONARIES_LANGUAGES_1 = ForeignKeys0.FK_DICTIONARIES_LANGUAGES_1;
    public static final ForeignKey<DictionariesRecord, DicttypesRecord> FK_DICTIONARIES_DICTTYPES_1 = ForeignKeys0.FK_DICTIONARIES_DICTTYPES_1;
    public static final ForeignKey<EtextbooksRecord, LanguagesRecord> FK_ETEXTBOOKS_LANGUAGES_1 = ForeignKeys0.FK_ETEXTBOOKS_LANGUAGES_1;
    public static final ForeignKey<LangphrasesRecord, LanguagesRecord> FK_LANGPHRASES_LANGUAGES_1 = ForeignKeys0.FK_LANGPHRASES_LANGUAGES_1;
    public static final ForeignKey<LangwordsRecord, LanguagesRecord> FK_LANGWORDS_LANGUAGES_1 = ForeignKeys0.FK_LANGWORDS_LANGUAGES_1;
    public static final ForeignKey<TextbooksRecord, LanguagesRecord> FK_TEXTBOOKS_LANGUAGES_1 = ForeignKeys0.FK_TEXTBOOKS_LANGUAGES_1;
    public static final ForeignKey<UnitphrasesRecord, TextbooksRecord> FK_UNITPHRASES_TEXTBOOKS_1 = ForeignKeys0.FK_UNITPHRASES_TEXTBOOKS_1;
    public static final ForeignKey<UnitphrasesRecord, LangphrasesRecord> FK_UNITPHRASES_LANGPHRASES_1 = ForeignKeys0.FK_UNITPHRASES_LANGPHRASES_1;
    public static final ForeignKey<UnitwordsRecord, TextbooksRecord> FK_UNITWORDS_TEXTBOOKS_1 = ForeignKeys0.FK_UNITWORDS_TEXTBOOKS_1;
    public static final ForeignKey<UsersettingsRecord, UsersRecord> FK_USERSETTINGS_USERS_1 = ForeignKeys0.FK_USERSETTINGS_USERS_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AutocorrectRecord> PK_AUTOCORRECT = createUniqueKey(Autocorrect.AUTOCORRECT, "pk_AUTOCORRECT", Autocorrect.AUTOCORRECT.ID);
        public static final UniqueKey<DictionariesRecord> PK_DICTIONARIES = createUniqueKey(Dictionaries.DICTIONARIES, "pk_DICTIONARIES", Dictionaries.DICTIONARIES.ID);
        public static final UniqueKey<DicttypesRecord> PK_DICTTYPES = createUniqueKey(Dicttypes.DICTTYPES, "pk_DICTTYPES", Dicttypes.DICTTYPES.ID);
        public static final UniqueKey<EtextbooksRecord> PK_ETEXTBOOKS = createUniqueKey(Etextbooks.ETEXTBOOKS, "pk_ETEXTBOOKS", Etextbooks.ETEXTBOOKS.ID);
        public static final UniqueKey<LangphrasesRecord> PK_LANGPHRASES = createUniqueKey(Langphrases.LANGPHRASES, "pk_LANGPHRASES", Langphrases.LANGPHRASES.ID);
        public static final UniqueKey<LanguagesRecord> PK_LANGUAGES = createUniqueKey(Languages.LANGUAGES, "pk_LANGUAGES", Languages.LANGUAGES.ID);
        public static final UniqueKey<LangwordsRecord> PK_LANGWORDS = createUniqueKey(Langwords.LANGWORDS, "pk_LANGWORDS", Langwords.LANGWORDS.ID);
        public static final UniqueKey<SitesRecord> PK_SITES = createUniqueKey(Sites.SITES, "pk_SITES", Sites.SITES.ID);
        public static final UniqueKey<TextbooksRecord> PK_TEXTBOOKS = createUniqueKey(Textbooks.TEXTBOOKS, "pk_TEXTBOOKS", Textbooks.TEXTBOOKS.ID);
        public static final UniqueKey<TextsitesRecord> PK_TEXTSITES = createUniqueKey(Textsites.TEXTSITES, "pk_TEXTSITES", Textsites.TEXTSITES.ID);
        public static final UniqueKey<UnitphrasesRecord> PK_UNITPHRASES = createUniqueKey(Unitphrases.UNITPHRASES, "pk_UNITPHRASES", Unitphrases.UNITPHRASES.ID);
        public static final UniqueKey<UnitwordsRecord> PK_UNITWORDS = createUniqueKey(Unitwords.UNITWORDS, "pk_UNITWORDS", Unitwords.UNITWORDS.ID);
        public static final UniqueKey<UsersRecord> PK_USERS = createUniqueKey(Users.USERS, "pk_USERS", Users.USERS.ID);
        public static final UniqueKey<UsersettingsRecord> PK_USERSETTINGS = createUniqueKey(Usersettings.USERSETTINGS, "pk_USERSETTINGS", Usersettings.USERSETTINGS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AutocorrectRecord, LanguagesRecord> FK_AUTOCORRECT_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Autocorrect.AUTOCORRECT, "fk_AUTOCORRECT_LANGUAGES_1", Autocorrect.AUTOCORRECT.LANGID);
        public static final ForeignKey<DictionariesRecord, LanguagesRecord> FK_DICTIONARIES_LANGUAGES_2 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Dictionaries.DICTIONARIES, "fk_DICTIONARIES_LANGUAGES_2", Dictionaries.DICTIONARIES.LANGIDFROM);
        public static final ForeignKey<DictionariesRecord, LanguagesRecord> FK_DICTIONARIES_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Dictionaries.DICTIONARIES, "fk_DICTIONARIES_LANGUAGES_1", Dictionaries.DICTIONARIES.LANGIDTO);
        public static final ForeignKey<DictionariesRecord, DicttypesRecord> FK_DICTIONARIES_DICTTYPES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_DICTTYPES, Dictionaries.DICTIONARIES, "fk_DICTIONARIES_DICTTYPES_1", Dictionaries.DICTIONARIES.DICTTYPEID);
        public static final ForeignKey<EtextbooksRecord, LanguagesRecord> FK_ETEXTBOOKS_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Etextbooks.ETEXTBOOKS, "fk_ETEXTBOOKS_LANGUAGES_1", Etextbooks.ETEXTBOOKS.LANGID);
        public static final ForeignKey<LangphrasesRecord, LanguagesRecord> FK_LANGPHRASES_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Langphrases.LANGPHRASES, "fk_LANGPHRASES_LANGUAGES_1", Langphrases.LANGPHRASES.LANGID);
        public static final ForeignKey<LangwordsRecord, LanguagesRecord> FK_LANGWORDS_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Langwords.LANGWORDS, "fk_LANGWORDS_LANGUAGES_1", Langwords.LANGWORDS.LANGID);
        public static final ForeignKey<TextbooksRecord, LanguagesRecord> FK_TEXTBOOKS_LANGUAGES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGUAGES, Textbooks.TEXTBOOKS, "fk_TEXTBOOKS_LANGUAGES_1", Textbooks.TEXTBOOKS.LANGID);
        public static final ForeignKey<UnitphrasesRecord, TextbooksRecord> FK_UNITPHRASES_TEXTBOOKS_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_TEXTBOOKS, Unitphrases.UNITPHRASES, "fk_UNITPHRASES_TEXTBOOKS_1", Unitphrases.UNITPHRASES.TEXTBOOKID);
        public static final ForeignKey<UnitphrasesRecord, LangphrasesRecord> FK_UNITPHRASES_LANGPHRASES_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_LANGPHRASES, Unitphrases.UNITPHRASES, "fk_UNITPHRASES_LANGPHRASES_1", Unitphrases.UNITPHRASES.LANGPHRASEID);
        public static final ForeignKey<UnitwordsRecord, TextbooksRecord> FK_UNITWORDS_TEXTBOOKS_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_TEXTBOOKS, Unitwords.UNITWORDS, "fk_UNITWORDS_TEXTBOOKS_1", Unitwords.UNITWORDS.TEXTBOOKID);
        public static final ForeignKey<UsersettingsRecord, UsersRecord> FK_USERSETTINGS_USERS_1 = createForeignKey(com.zwstudio.lolly.jooq.Keys.PK_USERS, Usersettings.USERSETTINGS, "fk_USERSETTINGS_USERS_1", Usersettings.USERSETTINGS.USERID);
    }
}
