/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq;


import com.zwstudio.lolly.jooq.tables.Autocorrect;
import com.zwstudio.lolly.jooq.tables.Dictionaries;
import com.zwstudio.lolly.jooq.tables.Dicttypes;
import com.zwstudio.lolly.jooq.tables.Etextbooks;
import com.zwstudio.lolly.jooq.tables.Langphrases;
import com.zwstudio.lolly.jooq.tables.Languages;
import com.zwstudio.lolly.jooq.tables.Langwords;
import com.zwstudio.lolly.jooq.tables.Sites;
import com.zwstudio.lolly.jooq.tables.Textbooks;
import com.zwstudio.lolly.jooq.tables.Textsites;
import com.zwstudio.lolly.jooq.tables.Unitphrases;
import com.zwstudio.lolly.jooq.tables.Unitwords;
import com.zwstudio.lolly.jooq.tables.Users;
import com.zwstudio.lolly.jooq.tables.Usersettings;
import com.zwstudio.lolly.jooq.tables.Vdictionaries;
import com.zwstudio.lolly.jooq.tables.Vetextbooks;
import com.zwstudio.lolly.jooq.tables.Vlanguages;
import com.zwstudio.lolly.jooq.tables.Vtextbooks;
import com.zwstudio.lolly.jooq.tables.Vtextbookwords;
import com.zwstudio.lolly.jooq.tables.Vtextsites;
import com.zwstudio.lolly.jooq.tables.Vunitphrases;
import com.zwstudio.lolly.jooq.tables.Vusersettings;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AUTOCORRECT</code>.
     */
    public static final Autocorrect AUTOCORRECT = com.zwstudio.lolly.jooq.tables.Autocorrect.AUTOCORRECT;

    /**
     * The table <code>DICTIONARIES</code>.
     */
    public static final Dictionaries DICTIONARIES = com.zwstudio.lolly.jooq.tables.Dictionaries.DICTIONARIES;

    /**
     * The table <code>DICTTYPES</code>.
     */
    public static final Dicttypes DICTTYPES = com.zwstudio.lolly.jooq.tables.Dicttypes.DICTTYPES;

    /**
     * The table <code>ETEXTBOOKS</code>.
     */
    public static final Etextbooks ETEXTBOOKS = com.zwstudio.lolly.jooq.tables.Etextbooks.ETEXTBOOKS;

    /**
     * The table <code>LANGPHRASES</code>.
     */
    public static final Langphrases LANGPHRASES = com.zwstudio.lolly.jooq.tables.Langphrases.LANGPHRASES;

    /**
     * The table <code>LANGUAGES</code>.
     */
    public static final Languages LANGUAGES = com.zwstudio.lolly.jooq.tables.Languages.LANGUAGES;

    /**
     * The table <code>LANGWORDS</code>.
     */
    public static final Langwords LANGWORDS = com.zwstudio.lolly.jooq.tables.Langwords.LANGWORDS;

    /**
     * The table <code>SITES</code>.
     */
    public static final Sites SITES = com.zwstudio.lolly.jooq.tables.Sites.SITES;

    /**
     * The table <code>TEXTBOOKS</code>.
     */
    public static final Textbooks TEXTBOOKS = com.zwstudio.lolly.jooq.tables.Textbooks.TEXTBOOKS;

    /**
     * The table <code>TEXTSITES</code>.
     */
    public static final Textsites TEXTSITES = com.zwstudio.lolly.jooq.tables.Textsites.TEXTSITES;

    /**
     * The table <code>UNITPHRASES</code>.
     */
    public static final Unitphrases UNITPHRASES = com.zwstudio.lolly.jooq.tables.Unitphrases.UNITPHRASES;

    /**
     * The table <code>UNITWORDS</code>.
     */
    public static final Unitwords UNITWORDS = com.zwstudio.lolly.jooq.tables.Unitwords.UNITWORDS;

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = com.zwstudio.lolly.jooq.tables.Users.USERS;

    /**
     * The table <code>USERSETTINGS</code>.
     */
    public static final Usersettings USERSETTINGS = com.zwstudio.lolly.jooq.tables.Usersettings.USERSETTINGS;

    /**
     * The table <code>VDICTIONARIES</code>.
     */
    public static final Vdictionaries VDICTIONARIES = com.zwstudio.lolly.jooq.tables.Vdictionaries.VDICTIONARIES;

    /**
     * The table <code>VETEXTBOOKS</code>.
     */
    public static final Vetextbooks VETEXTBOOKS = com.zwstudio.lolly.jooq.tables.Vetextbooks.VETEXTBOOKS;

    /**
     * The table <code>VLANGUAGES</code>.
     */
    public static final Vlanguages VLANGUAGES = com.zwstudio.lolly.jooq.tables.Vlanguages.VLANGUAGES;

    /**
     * The table <code>VTEXTBOOKS</code>.
     */
    public static final Vtextbooks VTEXTBOOKS = com.zwstudio.lolly.jooq.tables.Vtextbooks.VTEXTBOOKS;

    /**
     * The table <code>VTEXTBOOKWORDS</code>.
     */
    public static final Vtextbookwords VTEXTBOOKWORDS = com.zwstudio.lolly.jooq.tables.Vtextbookwords.VTEXTBOOKWORDS;

    /**
     * The table <code>VTEXTSITES</code>.
     */
    public static final Vtextsites VTEXTSITES = com.zwstudio.lolly.jooq.tables.Vtextsites.VTEXTSITES;

    /**
     * The table <code>VUNITPHRASES</code>.
     */
    public static final Vunitphrases VUNITPHRASES = com.zwstudio.lolly.jooq.tables.Vunitphrases.VUNITPHRASES;

    /**
     * The table <code>VUSERSETTINGS</code>.
     */
    public static final Vusersettings VUSERSETTINGS = com.zwstudio.lolly.jooq.tables.Vusersettings.VUSERSETTINGS;
}
