/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.Keys;
import com.zwstudio.lolly.jooq.tables.records.AutocorrectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Autocorrect extends TableImpl<AutocorrectRecord> {

    private static final long serialVersionUID = 296395982;

    /**
     * The reference instance of <code>AUTOCORRECT</code>
     */
    public static final Autocorrect AUTOCORRECT = new Autocorrect();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AutocorrectRecord> getRecordType() {
        return AutocorrectRecord.class;
    }

    /**
     * The column <code>AUTOCORRECT.ID</code>.
     */
    public final TableField<AutocorrectRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>AUTOCORRECT.LANGID</code>.
     */
    public final TableField<AutocorrectRecord, Integer> LANGID = createField("LANGID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>AUTOCORRECT.SEQNUM</code>.
     */
    public final TableField<AutocorrectRecord, Integer> SEQNUM = createField("SEQNUM", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>AUTOCORRECT.INPUT</code>.
     */
    public final TableField<AutocorrectRecord, String> INPUT = createField("INPUT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>AUTOCORRECT.EXTENDED</code>.
     */
    public final TableField<AutocorrectRecord, String> EXTENDED = createField("EXTENDED", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>AUTOCORRECT.BASIC</code>.
     */
    public final TableField<AutocorrectRecord, String> BASIC = createField("BASIC", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>AUTOCORRECT</code> table reference
     */
    public Autocorrect() {
        this("AUTOCORRECT", null);
    }

    /**
     * Create an aliased <code>AUTOCORRECT</code> table reference
     */
    public Autocorrect(String alias) {
        this(alias, AUTOCORRECT);
    }

    private Autocorrect(String alias, Table<AutocorrectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Autocorrect(String alias, Table<AutocorrectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AutocorrectRecord> getPrimaryKey() {
        return Keys.PK_AUTOCORRECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AutocorrectRecord>> getKeys() {
        return Arrays.<UniqueKey<AutocorrectRecord>>asList(Keys.PK_AUTOCORRECT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AutocorrectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AutocorrectRecord, ?>>asList(Keys.FK_AUTOCORRECT_LANGUAGES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Autocorrect as(String alias) {
        return new Autocorrect(alias, this);
    }

    /**
     * Rename this table
     */
    public Autocorrect rename(String name) {
        return new Autocorrect(name, null);
    }
}
