/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.Keys;
import com.zwstudio.lolly.jooq.tables.records.EtextbooksRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Etextbooks extends TableImpl<EtextbooksRecord> {

    private static final long serialVersionUID = 171615286;

    /**
     * The reference instance of <code>ETEXTBOOKS</code>
     */
    public static final Etextbooks ETEXTBOOKS = new Etextbooks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EtextbooksRecord> getRecordType() {
        return EtextbooksRecord.class;
    }

    /**
     * The column <code>ETEXTBOOKS.ID</code>.
     */
    public final TableField<EtextbooksRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ETEXTBOOKS.LANGID</code>.
     */
    public final TableField<EtextbooksRecord, Integer> LANGID = createField("LANGID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ETEXTBOOKS.NAME</code>.
     */
    public final TableField<EtextbooksRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ETEXTBOOKS.PAGES</code>.
     */
    public final TableField<EtextbooksRecord, Integer> PAGES = createField("PAGES", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("500", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>ETEXTBOOKS</code> table reference
     */
    public Etextbooks() {
        this("ETEXTBOOKS", null);
    }

    /**
     * Create an aliased <code>ETEXTBOOKS</code> table reference
     */
    public Etextbooks(String alias) {
        this(alias, ETEXTBOOKS);
    }

    private Etextbooks(String alias, Table<EtextbooksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Etextbooks(String alias, Table<EtextbooksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EtextbooksRecord> getPrimaryKey() {
        return Keys.PK_ETEXTBOOKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EtextbooksRecord>> getKeys() {
        return Arrays.<UniqueKey<EtextbooksRecord>>asList(Keys.PK_ETEXTBOOKS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EtextbooksRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EtextbooksRecord, ?>>asList(Keys.FK_ETEXTBOOKS_LANGUAGES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Etextbooks as(String alias) {
        return new Etextbooks(alias, this);
    }

    /**
     * Rename this table
     */
    public Etextbooks rename(String name) {
        return new Etextbooks(name, null);
    }
}
