/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.Keys;
import com.zwstudio.lolly.jooq.tables.records.LanguagesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Languages extends TableImpl<LanguagesRecord> {

    private static final long serialVersionUID = -1952122908;

    /**
     * The reference instance of <code>LANGUAGES</code>
     */
    public static final Languages LANGUAGES = new Languages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LanguagesRecord> getRecordType() {
        return LanguagesRecord.class;
    }

    /**
     * The column <code>LANGUAGES.ID</code>.
     */
    public final TableField<LanguagesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>LANGUAGES.NAME</code>.
     */
    public final TableField<LanguagesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>LANGUAGES.VOICE</code>.
     */
    public final TableField<LanguagesRecord, String> VOICE = createField("VOICE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>LANGUAGES.CHNNAME</code>.
     */
    public final TableField<LanguagesRecord, String> CHNNAME = createField("CHNNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>LANGUAGES.ENGNAME</code>.
     */
    public final TableField<LanguagesRecord, String> ENGNAME = createField("ENGNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>LANGUAGES</code> table reference
     */
    public Languages() {
        this("LANGUAGES", null);
    }

    /**
     * Create an aliased <code>LANGUAGES</code> table reference
     */
    public Languages(String alias) {
        this(alias, LANGUAGES);
    }

    private Languages(String alias, Table<LanguagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Languages(String alias, Table<LanguagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LanguagesRecord> getPrimaryKey() {
        return Keys.PK_LANGUAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LanguagesRecord>> getKeys() {
        return Arrays.<UniqueKey<LanguagesRecord>>asList(Keys.PK_LANGUAGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Languages as(String alias) {
        return new Languages(alias, this);
    }

    /**
     * Rename this table
     */
    public Languages rename(String name) {
        return new Languages(name, null);
    }
}
