/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.Keys;
import com.zwstudio.lolly.jooq.tables.records.TextsitesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Textsites extends TableImpl<TextsitesRecord> {

    private static final long serialVersionUID = 295772365;

    /**
     * The reference instance of <code>TEXTSITES</code>
     */
    public static final Textsites TEXTSITES = new Textsites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TextsitesRecord> getRecordType() {
        return TextsitesRecord.class;
    }

    /**
     * The column <code>TEXTSITES.ID</code>.
     */
    public final TableField<TextsitesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>TEXTSITES.NAME</code>.
     */
    public final TableField<TextsitesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>TEXTSITES.URL</code>.
     */
    public final TableField<TextsitesRecord, String> URL = createField("URL", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>TEXTSITES.TEMPLATE</code>.
     */
    public final TableField<TextsitesRecord, String> TEMPLATE = createField("TEMPLATE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>TEXTSITES</code> table reference
     */
    public Textsites() {
        this("TEXTSITES", null);
    }

    /**
     * Create an aliased <code>TEXTSITES</code> table reference
     */
    public Textsites(String alias) {
        this(alias, TEXTSITES);
    }

    private Textsites(String alias, Table<TextsitesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Textsites(String alias, Table<TextsitesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TextsitesRecord> getPrimaryKey() {
        return Keys.PK_TEXTSITES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TextsitesRecord>> getKeys() {
        return Arrays.<UniqueKey<TextsitesRecord>>asList(Keys.PK_TEXTSITES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Textsites as(String alias) {
        return new Textsites(alias, this);
    }

    /**
     * Rename this table
     */
    public Textsites rename(String name) {
        return new Textsites(name, null);
    }
}
