/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VetextbooksRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vetextbooks extends TableImpl<VetextbooksRecord> {

    private static final long serialVersionUID = -1197659291;

    /**
     * The reference instance of <code>VETEXTBOOKS</code>
     */
    public static final Vetextbooks VETEXTBOOKS = new Vetextbooks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VetextbooksRecord> getRecordType() {
        return VetextbooksRecord.class;
    }

    /**
     * The column <code>VETEXTBOOKS.ID</code>.
     */
    public final TableField<VetextbooksRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VETEXTBOOKS.LANGID</code>.
     */
    public final TableField<VetextbooksRecord, Integer> LANGID = createField("LANGID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VETEXTBOOKS.ETEXTBOOKNAME</code>.
     */
    public final TableField<VetextbooksRecord, String> ETEXTBOOKNAME = createField("ETEXTBOOKNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VETEXTBOOKS.PAGES</code>.
     */
    public final TableField<VetextbooksRecord, Integer> PAGES = createField("PAGES", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VETEXTBOOKS.USFILENAME</code>.
     */
    public final TableField<VetextbooksRecord, String> USFILENAME = createField("USFILENAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VETEXTBOOKS.USPAGE</code>.
     */
    public final TableField<VetextbooksRecord, String> USPAGE = createField("USPAGE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VETEXTBOOKS</code> table reference
     */
    public Vetextbooks() {
        this("VETEXTBOOKS", null);
    }

    /**
     * Create an aliased <code>VETEXTBOOKS</code> table reference
     */
    public Vetextbooks(String alias) {
        this(alias, VETEXTBOOKS);
    }

    private Vetextbooks(String alias, Table<VetextbooksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vetextbooks(String alias, Table<VetextbooksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vetextbooks as(String alias) {
        return new Vetextbooks(alias, this);
    }

    /**
     * Rename this table
     */
    public Vetextbooks rename(String name) {
        return new Vetextbooks(name, null);
    }
}
