/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VlanguagesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vlanguages extends TableImpl<VlanguagesRecord> {

    private static final long serialVersionUID = 814338573;

    /**
     * The reference instance of <code>VLANGUAGES</code>
     */
    public static final Vlanguages VLANGUAGES = new Vlanguages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VlanguagesRecord> getRecordType() {
        return VlanguagesRecord.class;
    }

    /**
     * The column <code>VLANGUAGES.ID</code>.
     */
    public final TableField<VlanguagesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VLANGUAGES.LANGNAME</code>.
     */
    public final TableField<VlanguagesRecord, String> LANGNAME = createField("LANGNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VLANGUAGES.VOICE</code>.
     */
    public final TableField<VlanguagesRecord, String> VOICE = createField("VOICE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VLANGUAGES.USTEXTBOOKID</code>.
     */
    public final TableField<VlanguagesRecord, String> USTEXTBOOKID = createField("USTEXTBOOKID", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VLANGUAGES.USDICTID</code>.
     */
    public final TableField<VlanguagesRecord, String> USDICTID = createField("USDICTID", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VLANGUAGES</code> table reference
     */
    public Vlanguages() {
        this("VLANGUAGES", null);
    }

    /**
     * Create an aliased <code>VLANGUAGES</code> table reference
     */
    public Vlanguages(String alias) {
        this(alias, VLANGUAGES);
    }

    private Vlanguages(String alias, Table<VlanguagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vlanguages(String alias, Table<VlanguagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vlanguages as(String alias) {
        return new Vlanguages(alias, this);
    }

    /**
     * Rename this table
     */
    public Vlanguages rename(String name) {
        return new Vlanguages(name, null);
    }
}
