/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VtextbookwordsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vtextbookwords extends TableImpl<VtextbookwordsRecord> {

    private static final long serialVersionUID = 2106706557;

    /**
     * The reference instance of <code>VTEXTBOOKWORDS</code>
     */
    public static final Vtextbookwords VTEXTBOOKWORDS = new Vtextbookwords();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VtextbookwordsRecord> getRecordType() {
        return VtextbookwordsRecord.class;
    }

    /**
     * The column <code>VTEXTBOOKWORDS.ID</code>.
     */
    public final TableField<VtextbookwordsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.LANGID</code>.
     */
    public final TableField<VtextbookwordsRecord, Integer> LANGID = createField("LANGID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.TEXTBOOKNAME</code>.
     */
    public final TableField<VtextbookwordsRecord, String> TEXTBOOKNAME = createField("TEXTBOOKNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.UNIT</code>.
     */
    public final TableField<VtextbookwordsRecord, Integer> UNIT = createField("UNIT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.PART</code>.
     */
    public final TableField<VtextbookwordsRecord, Integer> PART = createField("PART", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.SEQNUM</code>.
     */
    public final TableField<VtextbookwordsRecord, Integer> SEQNUM = createField("SEQNUM", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.WORD</code>.
     */
    public final TableField<VtextbookwordsRecord, String> WORD = createField("WORD", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKWORDS.NOTE</code>.
     */
    public final TableField<VtextbookwordsRecord, String> NOTE = createField("NOTE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VTEXTBOOKWORDS</code> table reference
     */
    public Vtextbookwords() {
        this("VTEXTBOOKWORDS", null);
    }

    /**
     * Create an aliased <code>VTEXTBOOKWORDS</code> table reference
     */
    public Vtextbookwords(String alias) {
        this(alias, VTEXTBOOKWORDS);
    }

    private Vtextbookwords(String alias, Table<VtextbookwordsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vtextbookwords(String alias, Table<VtextbookwordsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vtextbookwords as(String alias) {
        return new Vtextbookwords(alias, this);
    }

    /**
     * Rename this table
     */
    public Vtextbookwords rename(String name) {
        return new Vtextbookwords(name, null);
    }
}
