/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VtextbooksRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vtextbooks extends TableImpl<VtextbooksRecord> {

    private static final long serialVersionUID = 1433901455;

    /**
     * The reference instance of <code>VTEXTBOOKS</code>
     */
    public static final Vtextbooks VTEXTBOOKS = new Vtextbooks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VtextbooksRecord> getRecordType() {
        return VtextbooksRecord.class;
    }

    /**
     * The column <code>VTEXTBOOKS.ID</code>.
     */
    public final TableField<VtextbooksRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKS.LANGID</code>.
     */
    public final TableField<VtextbooksRecord, Integer> LANGID = createField("LANGID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKS.TEXTBOOKNAME</code>.
     */
    public final TableField<VtextbooksRecord, String> TEXTBOOKNAME = createField("TEXTBOOKNAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKS.UNITS</code>.
     */
    public final TableField<VtextbooksRecord, Integer> UNITS = createField("UNITS", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VTEXTBOOKS.PARTS</code>.
     */
    public final TableField<VtextbooksRecord, String> PARTS = createField("PARTS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKS.USUNITFROM</code>.
     */
    public final TableField<VtextbooksRecord, String> USUNITFROM = createField("USUNITFROM", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKS.USPARTFROM</code>.
     */
    public final TableField<VtextbooksRecord, String> USPARTFROM = createField("USPARTFROM", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKS.USUNITTO</code>.
     */
    public final TableField<VtextbooksRecord, String> USUNITTO = createField("USUNITTO", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VTEXTBOOKS.USPARTTO</code>.
     */
    public final TableField<VtextbooksRecord, String> USPARTTO = createField("USPARTTO", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VTEXTBOOKS</code> table reference
     */
    public Vtextbooks() {
        this("VTEXTBOOKS", null);
    }

    /**
     * Create an aliased <code>VTEXTBOOKS</code> table reference
     */
    public Vtextbooks(String alias) {
        this(alias, VTEXTBOOKS);
    }

    private Vtextbooks(String alias, Table<VtextbooksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vtextbooks(String alias, Table<VtextbooksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vtextbooks as(String alias) {
        return new Vtextbooks(alias, this);
    }

    /**
     * Rename this table
     */
    public Vtextbooks rename(String name) {
        return new Vtextbooks(name, null);
    }
}
