/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VunitphrasesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vunitphrases extends TableImpl<VunitphrasesRecord> {

    private static final long serialVersionUID = 732102874;

    /**
     * The reference instance of <code>VUNITPHRASES</code>
     */
    public static final Vunitphrases VUNITPHRASES = new Vunitphrases();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VunitphrasesRecord> getRecordType() {
        return VunitphrasesRecord.class;
    }

    /**
     * The column <code>VUNITPHRASES.ID</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.TEXTBOOKID</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> TEXTBOOKID = createField("TEXTBOOKID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.UNIT</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> UNIT = createField("UNIT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.PART</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> PART = createField("PART", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.SEQNUM</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> SEQNUM = createField("SEQNUM", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.LANGPHRASEID</code>.
     */
    public final TableField<VunitphrasesRecord, Integer> LANGPHRASEID = createField("LANGPHRASEID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUNITPHRASES.PHRASE</code>.
     */
    public final TableField<VunitphrasesRecord, String> PHRASE = createField("PHRASE", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>VUNITPHRASES.TRANSLATION</code>.
     */
    public final TableField<VunitphrasesRecord, String> TRANSLATION = createField("TRANSLATION", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VUNITPHRASES</code> table reference
     */
    public Vunitphrases() {
        this("VUNITPHRASES", null);
    }

    /**
     * Create an aliased <code>VUNITPHRASES</code> table reference
     */
    public Vunitphrases(String alias) {
        this(alias, VUNITPHRASES);
    }

    private Vunitphrases(String alias, Table<VunitphrasesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vunitphrases(String alias, Table<VunitphrasesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vunitphrases as(String alias) {
        return new Vunitphrases(alias, this);
    }

    /**
     * Rename this table
     */
    public Vunitphrases rename(String name) {
        return new Vunitphrases(name, null);
    }
}
