/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables;


import com.zwstudio.lolly.jooq.DefaultSchema;
import com.zwstudio.lolly.jooq.tables.records.VusersettingsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vusersettings extends TableImpl<VusersettingsRecord> {

    private static final long serialVersionUID = -1255996865;

    /**
     * The reference instance of <code>VUSERSETTINGS</code>
     */
    public static final Vusersettings VUSERSETTINGS = new Vusersettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VusersettingsRecord> getRecordType() {
        return VusersettingsRecord.class;
    }

    /**
     * The column <code>VUSERSETTINGS.ID</code>.
     */
    public final TableField<VusersettingsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUSERSETTINGS.USERID</code>.
     */
    public final TableField<VusersettingsRecord, Integer> USERID = createField("USERID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUSERSETTINGS.ENTITYID</code>.
     */
    public final TableField<VusersettingsRecord, Integer> ENTITYID = createField("ENTITYID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>VUSERSETTINGS.USLANGID</code>.
     */
    public final TableField<VusersettingsRecord, String> USLANGID = createField("USLANGID", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>VUSERSETTINGS</code> table reference
     */
    public Vusersettings() {
        this("VUSERSETTINGS", null);
    }

    /**
     * Create an aliased <code>VUSERSETTINGS</code> table reference
     */
    public Vusersettings(String alias) {
        this(alias, VUSERSETTINGS);
    }

    private Vusersettings(String alias, Table<VusersettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vusersettings(String alias, Table<VusersettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vusersettings as(String alias) {
        return new Vusersettings(alias, this);
    }

    /**
     * Rename this table
     */
    public Vusersettings rename(String name) {
        return new Vusersettings(name, null);
    }
}
