DROP TABLE VDICTIONARIES2;
CREATE TABLE VDICTIONARIES2 AS SELECT * FROM VDICTIONARIES WHERE 1 <> 1;
DROP TABLE VLANGUAGES2;
CREATE TABLE VLANGUAGES2 AS SELECT * FROM VLANGUAGES WHERE 1 <> 1;
DROP TABLE VTEXTBOOKS2;
CREATE TABLE VTEXTBOOKS2 AS SELECT * FROM VTEXTBOOKS WHERE 1 <> 1;