package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * AutoCorrect generated by hbm2java
 */
public class AutoCorrect implements java.io.Serializable {

	private int id;
	private Language language;
	private int index;
	private String input;
	private String extended;
	private String basic;

	public AutoCorrect() {
	}

	public AutoCorrect(int id, Language language, int index, String input,
			String extended, String basic) {
		this.id = id;
		this.language = language;
		this.index = index;
		this.input = input;
		this.extended = extended;
		this.basic = basic;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public String getInput() {
		return this.input;
	}

	public void setInput(String input) {
		this.input = input;
	}

	public String getExtended() {
		return this.extended;
	}

	public void setExtended(String extended) {
		this.extended = extended;
	}

	public String getBasic() {
		return this.basic;
	}

	public void setBasic(String basic) {
		this.basic = basic;
	}

}
