package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private int bookid;
	private int langid;
	private String bookname;
	private int numlessons;
	private String parts;
	private int lessonfrom;
	private int partfrom;
	private int lessonto;
	private int partto;

	public Book() {
	}

	public Book(int bookid, int langid, String bookname, int numlessons,
			String parts, int lessonfrom, int partfrom, int lessonto, int partto) {
		this.bookid = bookid;
		this.langid = langid;
		this.bookname = bookname;
		this.numlessons = numlessons;
		this.parts = parts;
		this.lessonfrom = lessonfrom;
		this.partfrom = partfrom;
		this.lessonto = lessonto;
		this.partto = partto;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public int getNumlessons() {
		return this.numlessons;
	}

	public void setNumlessons(int numlessons) {
		this.numlessons = numlessons;
	}

	public String getParts() {
		return this.parts;
	}

	public void setParts(String parts) {
		this.parts = parts;
	}

	public int getLessonfrom() {
		return this.lessonfrom;
	}

	public void setLessonfrom(int lessonfrom) {
		this.lessonfrom = lessonfrom;
	}

	public int getPartfrom() {
		return this.partfrom;
	}

	public void setPartfrom(int partfrom) {
		this.partfrom = partfrom;
	}

	public int getLessonto() {
		return this.lessonto;
	}

	public void setLessonto(int lessonto) {
		this.lessonto = lessonto;
	}

	public int getPartto() {
		return this.partto;
	}

	public void setPartto(int partto) {
		this.partto = partto;
	}

}
