package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DictAllId generated by hbm2java
 */
@Embeddable
public class DictAllId implements java.io.Serializable {

	private Integer langid;
	private Integer index;

	public DictAllId() {
	}

	public DictAllId(Integer langid, Integer index) {
		this.langid = langid;
		this.index = index;
	}

	@Column(name = "LANGID")
	public Integer getLangid() {
		return this.langid;
	}

	public void setLangid(Integer langid) {
		this.langid = langid;
	}

	@Column(name = "INDEX")
	public Integer getIndex() {
		return this.index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DictAllId))
			return false;
		DictAllId castOther = (DictAllId) other;

		return ((this.getLangid() == castOther.getLangid()) || (this
				.getLangid() != null && castOther.getLangid() != null && this
				.getLangid().equals(castOther.getLangid())))
				&& ((this.getIndex() == castOther.getIndex()) || (this
						.getIndex() != null && castOther.getIndex() != null && this
						.getIndex().equals(castOther.getIndex())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLangid() == null ? 0 : this.getLangid().hashCode());
		result = 37 * result
				+ (getIndex() == null ? 0 : this.getIndex().hashCode());
		return result;
	}

}
