package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	private DictionaryId id;
	private int index;
	private int dicttypeid;
	private int langidto;
	private String url;
	private String chconv;
	private String automation;
	private int autojump;
	private String dicttable;
	private String template;

	public Dictionary() {
	}

	public Dictionary(DictionaryId id, int index, int dicttypeid, int langidto,
			int autojump) {
		this.id = id;
		this.index = index;
		this.dicttypeid = dicttypeid;
		this.langidto = langidto;
		this.autojump = autojump;
	}

	public Dictionary(DictionaryId id, int index, int dicttypeid, int langidto,
			String url, String chconv, String automation, int autojump,
			String dicttable, String template) {
		this.id = id;
		this.index = index;
		this.dicttypeid = dicttypeid;
		this.langidto = langidto;
		this.url = url;
		this.chconv = chconv;
		this.automation = automation;
		this.autojump = autojump;
		this.dicttable = dicttable;
		this.template = template;
	}

	public DictionaryId getId() {
		return this.id;
	}

	public void setId(DictionaryId id) {
		this.id = id;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public int getDicttypeid() {
		return this.dicttypeid;
	}

	public void setDicttypeid(int dicttypeid) {
		this.dicttypeid = dicttypeid;
	}

	public int getLangidto() {
		return this.langidto;
	}

	public void setLangidto(int langidto) {
		this.langidto = langidto;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getChconv() {
		return this.chconv;
	}

	public void setChconv(String chconv) {
		this.chconv = chconv;
	}

	public String getAutomation() {
		return this.automation;
	}

	public void setAutomation(String automation) {
		this.automation = automation;
	}

	public int getAutojump() {
		return this.autojump;
	}

	public void setAutojump(int autojump) {
		this.autojump = autojump;
	}

	public String getDicttable() {
		return this.dicttable;
	}

	public void setDicttable(String dicttable) {
		this.dicttable = dicttable;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

}
