package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private int langid;
	private String langname;
	private String chnname;
	private String voice;
	private Integer curbookid;
	private String engname;
	private Set autoCorrects = new HashSet(0);

	public Language() {
	}

	public Language(int langid, String langname, String chnname) {
		this.langid = langid;
		this.langname = langname;
		this.chnname = chnname;
	}

	public Language(int langid, String langname, String chnname, String voice,
			Integer curbookid, String engname, Set autoCorrects) {
		this.langid = langid;
		this.langname = langname;
		this.chnname = chnname;
		this.voice = voice;
		this.curbookid = curbookid;
		this.engname = engname;
		this.autoCorrects = autoCorrects;
	}

	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	public String getLangname() {
		return this.langname;
	}

	public void setLangname(String langname) {
		this.langname = langname;
	}

	public String getChnname() {
		return this.chnname;
	}

	public void setChnname(String chnname) {
		this.chnname = chnname;
	}

	public String getVoice() {
		return this.voice;
	}

	public void setVoice(String voice) {
		this.voice = voice;
	}

	public Integer getCurbookid() {
		return this.curbookid;
	}

	public void setCurbookid(Integer curbookid) {
		this.curbookid = curbookid;
	}

	public String getEngname() {
		return this.engname;
	}

	public void setEngname(String engname) {
		this.engname = engname;
	}

	public Set getAutoCorrects() {
		return this.autoCorrects;
	}

	public void setAutoCorrects(Set autoCorrects) {
		this.autoCorrects = autoCorrects;
	}

}
