package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Phrase generated by hbm2java
 */
public class Phrase implements java.io.Serializable {

	private int id;
	private int bookid;
	private int lesson;
	private int part;
	private int index;
	private String phrase;
	private String translation;

	public Phrase() {
	}

	public Phrase(int id, int bookid, int lesson, int part, int index,
			String phrase) {
		this.id = id;
		this.bookid = bookid;
		this.lesson = lesson;
		this.part = part;
		this.index = index;
		this.phrase = phrase;
	}

	public Phrase(int id, int bookid, int lesson, int part, int index,
			String phrase, String translation) {
		this.id = id;
		this.bookid = bookid;
		this.lesson = lesson;
		this.part = part;
		this.index = index;
		this.phrase = phrase;
		this.translation = translation;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public int getLesson() {
		return this.lesson;
	}

	public void setLesson(int lesson) {
		this.lesson = lesson;
	}

	public int getPart() {
		return this.part;
	}

	public void setPart(int part) {
		this.part = part;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public String getPhrase() {
		return this.phrase;
	}

	public void setPhrase(String phrase) {
		this.phrase = phrase;
	}

	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

}
