package com.zwstudio.lolly.domain;

// Generated 2014-9-29 23:34:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Phrase generated by hbm2java
 */
@Entity
@Table(name = "PHRASES")
public class Phrase implements java.io.Serializable {

	private int id;
	private int bookid;
	private int unit;
	private int part;
	private int index;
	private String phrase;
	private String translation;

	public Phrase() {
	}

	public Phrase(int id, int bookid, int unit, int part, int index,
			String phrase) {
		this.id = id;
		this.bookid = bookid;
		this.unit = unit;
		this.part = part;
		this.index = index;
		this.phrase = phrase;
	}

	public Phrase(int id, int bookid, int unit, int part, int index,
			String phrase, String translation) {
		this.id = id;
		this.bookid = bookid;
		this.unit = unit;
		this.part = part;
		this.index = index;
		this.phrase = phrase;
		this.translation = translation;
	}

	@Id
	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "BOOKID", nullable = false)
	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	@Column(name = "UNIT", nullable = false)
	public int getUnit() {
		return this.unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@Column(name = "PART", nullable = false)
	public int getPart() {
		return this.part;
	}

	public void setPart(int part) {
		this.part = part;
	}

	@Column(name = "INDEX", nullable = false)
	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	@Column(name = "PHRASE", nullable = false, length = 2000000000)
	public String getPhrase() {
		return this.phrase;
	}

	public void setPhrase(String phrase) {
		this.phrase = phrase;
	}

	@Column(name = "TRANSLATION", length = 2000000000)
	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

}
