package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Pickbook generated by hbm2java
 */
public class Pickbook implements java.io.Serializable {

	private String bookname;
	private int langid;
	private String filename;
	private int numpages;
	private int curpage;

	public Pickbook() {
	}

	public Pickbook(String bookname, int langid, String filename, int numpages,
			int curpage) {
		this.bookname = bookname;
		this.langid = langid;
		this.filename = filename;
		this.numpages = numpages;
		this.curpage = curpage;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public int getNumpages() {
		return this.numpages;
	}

	public void setNumpages(int numpages) {
		this.numpages = numpages;
	}

	public int getCurpage() {
		return this.curpage;
	}

	public void setCurpage(int curpage) {
		this.curpage = curpage;
	}

}
