package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class Users implements java.io.Serializable {

	private int userid;
	private String username;
	private String password;

	public Users() {
	}

	public Users(int userid, String username) {
		this.userid = userid;
		this.username = username;
	}

	public Users(int userid, String username, String password) {
		this.userid = userid;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "USERID", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "USERNAME", nullable = false, length = 2000000000)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 2000000000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
