package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int userid;
	private String username;
	private String password;

	public Users() {
	}

	public Users(int userid, String username) {
		this.userid = userid;
		this.username = username;
	}

	public Users(int userid, String username, String password) {
		this.userid = userid;
		this.username = username;
		this.password = password;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
