package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Webextract generated by hbm2java
 */
public class Webextract implements java.io.Serializable {

	private String sitename;
	private String transformWin;
	private String transformMac;
	private Integer wait;

	public Webextract() {
	}

	public Webextract(String sitename) {
		this.sitename = sitename;
	}

	public Webextract(String sitename, String transformWin,
			String transformMac, Integer wait) {
		this.sitename = sitename;
		this.transformWin = transformWin;
		this.transformMac = transformMac;
		this.wait = wait;
	}

	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getTransformWin() {
		return this.transformWin;
	}

	public void setTransformWin(String transformWin) {
		this.transformWin = transformWin;
	}

	public String getTransformMac() {
		return this.transformMac;
	}

	public void setTransformMac(String transformMac) {
		this.transformMac = transformMac;
	}

	public Integer getWait() {
		return this.wait;
	}

	public void setWait(Integer wait) {
		this.wait = wait;
	}

}
