package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Webextract generated by hbm2java
 */
@Entity
@Table(name = "WEBEXTRACT")
public class Webextract implements java.io.Serializable {

	private String sitename;
	private String transformWin;
	private String transformMac;
	private Integer wait;

	public Webextract() {
	}

	public Webextract(String sitename) {
		this.sitename = sitename;
	}

	public Webextract(String sitename, String transformWin,
			String transformMac, Integer wait) {
		this.sitename = sitename;
		this.transformWin = transformWin;
		this.transformMac = transformMac;
		this.wait = wait;
	}

	@Id
	@Column(name = "SITENAME", unique = true, nullable = false, length = 2000000000)
	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	@Column(name = "TRANSFORM_WIN", length = 2000000000)
	public String getTransformWin() {
		return this.transformWin;
	}

	public void setTransformWin(String transformWin) {
		this.transformWin = transformWin;
	}

	@Column(name = "TRANSFORM_MAC", length = 2000000000)
	public String getTransformMac() {
		return this.transformMac;
	}

	public void setTransformMac(String transformMac) {
		this.transformMac = transformMac;
	}

	@Column(name = "WAIT")
	public Integer getWait() {
		return this.wait;
	}

	public void setWait(Integer wait) {
		this.wait = wait;
	}

}
