package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Webtext generated by hbm2java
 */
public class Webtext implements java.io.Serializable {

	private String sitename;
	private String url;
	private String template;
	private String folder;

	public Webtext() {
	}

	public Webtext(String sitename) {
		this.sitename = sitename;
	}

	public Webtext(String sitename, String url, String template, String folder) {
		this.sitename = sitename;
		this.url = url;
		this.template = template;
		this.folder = folder;
	}

	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getFolder() {
		return this.folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

}
