package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Webtext generated by hbm2java
 */
@Entity
@Table(name = "WEBTEXT")
public class Webtext implements java.io.Serializable {

	private String sitename;
	private String url;
	private String template;
	private String folder;

	public Webtext() {
	}

	public Webtext(String sitename) {
		this.sitename = sitename;
	}

	public Webtext(String sitename, String url, String template, String folder) {
		this.sitename = sitename;
		this.url = url;
		this.template = template;
		this.folder = folder;
	}

	@Id
	@Column(name = "SITENAME", unique = true, nullable = false, length = 2000000000)
	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	@Column(name = "URL", length = 2000000000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "TEMPLATE", length = 2000000000)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "FOLDER", length = 2000000000)
	public String getFolder() {
		return this.folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

}
