package com.zwstudio.lolly.domain;

// Generated 2014-9-29 23:34:43 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Wordslang generated by hbm2java
 */
@Entity
@Table(name = "WORDSLANG")
public class Wordslang implements java.io.Serializable {

	private WordslangId id;
	private int level;

	public Wordslang() {
	}

	public Wordslang(WordslangId id, int level) {
		this.id = id;
		this.level = level;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "langid", column = @Column(name = "LANGID", nullable = false)),
			@AttributeOverride(name = "word", column = @Column(name = "WORD", nullable = false, length = 2000000000)) })
	public WordslangId getId() {
		return this.id;
	}

	public void setId(WordslangId id) {
		this.id = id;
	}

	@Column(name = "LEVEL", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
