package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Wordsbook generated by hbm2java
 */
public class Wordsbook implements java.io.Serializable {

	private int id;
	private int bookid;
	private int lesson;
	private int part;
	private int index;
	private String word;
	private String note;

	public Wordsbook() {
	}

	public Wordsbook(int id, int bookid, int lesson, int part, int index,
			String word) {
		this.id = id;
		this.bookid = bookid;
		this.lesson = lesson;
		this.part = part;
		this.index = index;
		this.word = word;
	}

	public Wordsbook(int id, int bookid, int lesson, int part, int index,
			String word, String note) {
		this.id = id;
		this.bookid = bookid;
		this.lesson = lesson;
		this.part = part;
		this.index = index;
		this.word = word;
		this.note = note;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public int getLesson() {
		return this.lesson;
	}

	public void setLesson(int lesson) {
		this.lesson = lesson;
	}

	public int getPart() {
		return this.part;
	}

	public void setPart(int part) {
		this.part = part;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
