package com.zwstudio.lolly.domain;

// Generated 2014-9-29 23:34:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WordslangId generated by hbm2java
 */
@Embeddable
public class WordslangId implements java.io.Serializable {

	private int langid;
	private String word;

	public WordslangId() {
	}

	public WordslangId(int langid, String word) {
		this.langid = langid;
		this.word = word;
	}

	@Column(name = "LANGID", nullable = false)
	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	@Column(name = "WORD", nullable = false, length = 2000000000)
	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WordslangId))
			return false;
		WordslangId castOther = (WordslangId) other;

		return (this.getLangid() == castOther.getLangid())
				&& ((this.getWord() == castOther.getWord()) || (this.getWord() != null
						&& castOther.getWord() != null && this.getWord()
						.equals(castOther.getWord())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLangid();
		result = 37 * result
				+ (getWord() == null ? 0 : this.getWord().hashCode());
		return result;
	}

}
