package com.zwstudio.lolly.domain;

// Generated 2014-9-28 14:08:58 by Hibernate Tools 4.3.1

/**
 * Wordslang generated by hbm2java
 */
public class Wordslang implements java.io.Serializable {

	private WordslangId id;
	private int level;

	public Wordslang() {
	}

	public Wordslang(WordslangId id, int level) {
		this.id = id;
		this.level = level;
	}

	public WordslangId getId() {
		return this.id;
	}

	public void setId(WordslangId id) {
		this.id = id;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
