/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Autocorrect;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutocorrectRecord extends UpdatableRecordImpl<AutocorrectRecord> implements Record6<Integer, Integer, Integer, String, String, String> {

    private static final long serialVersionUID = -1950929734;

    /**
     * Setter for <code>AUTOCORRECT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AUTOCORRECT.LANGID</code>.
     */
    public void setLangid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.LANGID</code>.
     */
    public Integer getLangid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>AUTOCORRECT.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>AUTOCORRECT.INPUT</code>.
     */
    public void setInput(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.INPUT</code>.
     */
    public String getInput() {
        return (String) get(3);
    }

    /**
     * Setter for <code>AUTOCORRECT.EXTENDED</code>.
     */
    public void setExtended(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.EXTENDED</code>.
     */
    public String getExtended() {
        return (String) get(4);
    }

    /**
     * Setter for <code>AUTOCORRECT.BASIC</code>.
     */
    public void setBasic(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>AUTOCORRECT.BASIC</code>.
     */
    public String getBasic() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Autocorrect.AUTOCORRECT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Autocorrect.AUTOCORRECT.LANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Autocorrect.AUTOCORRECT.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Autocorrect.AUTOCORRECT.INPUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Autocorrect.AUTOCORRECT.EXTENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Autocorrect.AUTOCORRECT.BASIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInput();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExtended();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBasic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value2(Integer value) {
        setLangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value3(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value4(String value) {
        setInput(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value5(String value) {
        setExtended(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord value6(String value) {
        setBasic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutocorrectRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AutocorrectRecord
     */
    public AutocorrectRecord() {
        super(Autocorrect.AUTOCORRECT);
    }

    /**
     * Create a detached, initialised AutocorrectRecord
     */
    public AutocorrectRecord(Integer id, Integer langid, Integer seqnum, String input, String extended, String basic) {
        super(Autocorrect.AUTOCORRECT);

        set(0, id);
        set(1, langid);
        set(2, seqnum);
        set(3, input);
        set(4, extended);
        set(5, basic);
    }
}
