/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Dictionaries;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictionariesRecord extends UpdatableRecordImpl<DictionariesRecord> implements Record12<Integer, Integer, Integer, String, Integer, Integer, String, String, String, Object, String, String> {

    private static final long serialVersionUID = -2003707320;

    /**
     * Setter for <code>DICTIONARIES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DICTIONARIES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DICTIONARIES.LANGIDFROM</code>.
     */
    public void setLangidfrom(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DICTIONARIES.LANGIDFROM</code>.
     */
    public Integer getLangidfrom() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DICTIONARIES.LANGIDTO</code>.
     */
    public void setLangidto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DICTIONARIES.LANGIDTO</code>.
     */
    public Integer getLangidto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DICTIONARIES.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DICTIONARIES.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DICTIONARIES.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DICTIONARIES.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DICTIONARIES.DICTTYPEID</code>.
     */
    public void setDicttypeid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DICTIONARIES.DICTTYPEID</code>.
     */
    public Integer getDicttypeid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DICTIONARIES.URL</code>.
     */
    public void setUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DICTIONARIES.URL</code>.
     */
    public String getUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DICTIONARIES.CHCONV</code>.
     */
    public void setChconv(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DICTIONARIES.CHCONV</code>.
     */
    public String getChconv() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DICTIONARIES.AUTOMATION</code>.
     */
    public void setAutomation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DICTIONARIES.AUTOMATION</code>.
     */
    public String getAutomation() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DICTIONARIES.AUTOJUMP</code>.
     */
    public void setAutojump(Object value) {
        set(9, value);
    }

    /**
     * Getter for <code>DICTIONARIES.AUTOJUMP</code>.
     */
    public Object getAutojump() {
        return (Object) get(9);
    }

    /**
     * Setter for <code>DICTIONARIES.DICTTABLE</code>.
     */
    public void setDicttable(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>DICTIONARIES.DICTTABLE</code>.
     */
    public String getDicttable() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DICTIONARIES.TEMPLATE</code>.
     */
    public void setTemplate(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>DICTIONARIES.TEMPLATE</code>.
     */
    public String getTemplate() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, String, Integer, Integer, String, String, String, Object, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, String, Integer, Integer, String, String, String, Object, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Dictionaries.DICTIONARIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Dictionaries.DICTIONARIES.LANGIDFROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Dictionaries.DICTIONARIES.LANGIDTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Dictionaries.DICTIONARIES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Dictionaries.DICTIONARIES.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Dictionaries.DICTIONARIES.DICTTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Dictionaries.DICTIONARIES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Dictionaries.DICTIONARIES.CHCONV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Dictionaries.DICTIONARIES.AUTOMATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field10() {
        return Dictionaries.DICTIONARIES.AUTOJUMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Dictionaries.DICTIONARIES.DICTTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Dictionaries.DICTIONARIES.TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangidfrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLangidto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDicttypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getChconv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAutomation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value10() {
        return getAutojump();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDicttable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value2(Integer value) {
        setLangidfrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value3(Integer value) {
        setLangidto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value5(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value6(Integer value) {
        setDicttypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value7(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value8(String value) {
        setChconv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value9(String value) {
        setAutomation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value10(Object value) {
        setAutojump(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value11(String value) {
        setDicttable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord value12(String value) {
        setTemplate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionariesRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, String value7, String value8, String value9, Object value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictionariesRecord
     */
    public DictionariesRecord() {
        super(Dictionaries.DICTIONARIES);
    }

    /**
     * Create a detached, initialised DictionariesRecord
     */
    public DictionariesRecord(Integer id, Integer langidfrom, Integer langidto, String name, Integer seqnum, Integer dicttypeid, String url, String chconv, String automation, Object autojump, String dicttable, String template) {
        super(Dictionaries.DICTIONARIES);

        set(0, id);
        set(1, langidfrom);
        set(2, langidto);
        set(3, name);
        set(4, seqnum);
        set(5, dicttypeid);
        set(6, url);
        set(7, chconv);
        set(8, automation);
        set(9, autojump);
        set(10, dicttable);
        set(11, template);
    }
}
