/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Langwords;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangwordsRecord extends UpdatableRecordImpl<LangwordsRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 1917194623;

    /**
     * Setter for <code>LANGWORDS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LANGWORDS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LANGWORDS.LANGID</code>.
     */
    public void setLangid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>LANGWORDS.LANGID</code>.
     */
    public Integer getLangid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>LANGWORDS.WORD</code>.
     */
    public void setWord(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LANGWORDS.WORD</code>.
     */
    public String getWord() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LANGWORDS.LEVEL</code>.
     */
    public void setLevel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>LANGWORDS.LEVEL</code>.
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langwords.LANGWORDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Langwords.LANGWORDS.LANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Langwords.LANGWORDS.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Langwords.LANGWORDS.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangwordsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangwordsRecord value2(Integer value) {
        setLangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangwordsRecord value3(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangwordsRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangwordsRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangwordsRecord
     */
    public LangwordsRecord() {
        super(Langwords.LANGWORDS);
    }

    /**
     * Create a detached, initialised LangwordsRecord
     */
    public LangwordsRecord(Integer id, Integer langid, String word, Integer level) {
        super(Langwords.LANGWORDS);

        set(0, id);
        set(1, langid);
        set(2, word);
        set(3, level);
    }
}
