/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Langphrases;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangphrasesRecord extends UpdatableRecordImpl<LangphrasesRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -1015539612;

    /**
     * Setter for <code>LANGPHRASES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LANGPHRASES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LANGPHRASES.LANGID</code>.
     */
    public void setLangid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>LANGPHRASES.LANGID</code>.
     */
    public Integer getLangid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>LANGPHRASES.PHRASE</code>.
     */
    public void setPhrase(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LANGPHRASES.PHRASE</code>.
     */
    public String getPhrase() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LANGPHRASES.TRANSLATION</code>.
     */
    public void setTranslation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>LANGPHRASES.TRANSLATION</code>.
     */
    public String getTranslation() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langphrases.LANGPHRASES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Langphrases.LANGPHRASES.LANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Langphrases.LANGPHRASES.PHRASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Langphrases.LANGPHRASES.TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhrase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangphrasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangphrasesRecord value2(Integer value) {
        setLangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangphrasesRecord value3(String value) {
        setPhrase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangphrasesRecord value4(String value) {
        setTranslation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangphrasesRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangphrasesRecord
     */
    public LangphrasesRecord() {
        super(Langphrases.LANGPHRASES);
    }

    /**
     * Create a detached, initialised LangphrasesRecord
     */
    public LangphrasesRecord(Integer id, Integer langid, String phrase, String translation) {
        super(Langphrases.LANGPHRASES);

        set(0, id);
        set(1, langid);
        set(2, phrase);
        set(3, translation);
    }
}
