/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Sites;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitesRecord extends UpdatableRecordImpl<SitesRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -1883848067;

    /**
     * Setter for <code>SITES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SITES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SITES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SITES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SITES.TRANSFORM_WIN</code>.
     */
    public void setTransformWin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SITES.TRANSFORM_WIN</code>.
     */
    public String getTransformWin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SITES.TRANSFORM_MAC</code>.
     */
    public void setTransformMac(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SITES.TRANSFORM_MAC</code>.
     */
    public String getTransformMac() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SITES.WAIT</code>.
     */
    public void setWait(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>SITES.WAIT</code>.
     */
    public Integer getWait() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Sites.SITES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Sites.SITES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Sites.SITES.TRANSFORM_WIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Sites.SITES.TRANSFORM_MAC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Sites.SITES.WAIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTransformWin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTransformMac();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWait();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord value3(String value) {
        setTransformWin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord value4(String value) {
        setTransformMac(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord value5(Integer value) {
        setWait(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SitesRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SitesRecord
     */
    public SitesRecord() {
        super(Sites.SITES);
    }

    /**
     * Create a detached, initialised SitesRecord
     */
    public SitesRecord(Integer id, String name, String transformWin, String transformMac, Integer wait) {
        super(Sites.SITES);

        set(0, id);
        set(1, name);
        set(2, transformWin);
        set(3, transformMac);
        set(4, wait);
    }
}
