/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Textbooks;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextbooksRecord extends UpdatableRecordImpl<TextbooksRecord> implements Record5<Integer, Integer, String, Integer, String> {

    private static final long serialVersionUID = 1173402513;

    /**
     * Setter for <code>TEXTBOOKS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TEXTBOOKS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TEXTBOOKS.LANGID</code>.
     */
    public void setLangid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TEXTBOOKS.LANGID</code>.
     */
    public Integer getLangid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TEXTBOOKS.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TEXTBOOKS.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TEXTBOOKS.UNITS</code>.
     */
    public void setUnits(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TEXTBOOKS.UNITS</code>.
     */
    public Integer getUnits() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TEXTBOOKS.PARTS</code>.
     */
    public void setParts(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>TEXTBOOKS.PARTS</code>.
     */
    public String getParts() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Textbooks.TEXTBOOKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Textbooks.TEXTBOOKS.LANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Textbooks.TEXTBOOKS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Textbooks.TEXTBOOKS.UNITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Textbooks.TEXTBOOKS.PARTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUnits();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getParts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord value2(Integer value) {
        setLangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord value4(Integer value) {
        setUnits(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord value5(String value) {
        setParts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextbooksRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TextbooksRecord
     */
    public TextbooksRecord() {
        super(Textbooks.TEXTBOOKS);
    }

    /**
     * Create a detached, initialised TextbooksRecord
     */
    public TextbooksRecord(Integer id, Integer langid, String name, Integer units, String parts) {
        super(Textbooks.TEXTBOOKS);

        set(0, id);
        set(1, langid);
        set(2, name);
        set(3, units);
        set(4, parts);
    }
}
