/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Unitphrases;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitphrasesRecord extends UpdatableRecordImpl<UnitphrasesRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1307486921;

    /**
     * Setter for <code>UNITPHRASES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>UNITPHRASES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>UNITPHRASES.TEXTBOOKID</code>.
     */
    public void setTextbookid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>UNITPHRASES.TEXTBOOKID</code>.
     */
    public Integer getTextbookid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>UNITPHRASES.UNIT</code>.
     */
    public void setUnit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>UNITPHRASES.UNIT</code>.
     */
    public Integer getUnit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>UNITPHRASES.PART</code>.
     */
    public void setPart(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>UNITPHRASES.PART</code>.
     */
    public Integer getPart() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>UNITPHRASES.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>UNITPHRASES.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>UNITPHRASES.LANGPHRASEID</code>.
     */
    public void setLangphraseid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>UNITPHRASES.LANGPHRASEID</code>.
     */
    public Integer getLangphraseid() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Unitphrases.UNITPHRASES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Unitphrases.UNITPHRASES.TEXTBOOKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Unitphrases.UNITPHRASES.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Unitphrases.UNITPHRASES.PART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Unitphrases.UNITPHRASES.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Unitphrases.UNITPHRASES.LANGPHRASEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTextbookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLangphraseid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value2(Integer value) {
        setTextbookid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value3(Integer value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value4(Integer value) {
        setPart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value5(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord value6(Integer value) {
        setLangphraseid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitphrasesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitphrasesRecord
     */
    public UnitphrasesRecord() {
        super(Unitphrases.UNITPHRASES);
    }

    /**
     * Create a detached, initialised UnitphrasesRecord
     */
    public UnitphrasesRecord(Integer id, Integer textbookid, Integer unit, Integer part, Integer seqnum, Integer langphraseid) {
        super(Unitphrases.UNITPHRASES);

        set(0, id);
        set(1, textbookid);
        set(2, unit);
        set(3, part);
        set(4, seqnum);
        set(5, langphraseid);
    }
}
