/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Unitwords;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitwordsRecord extends UpdatableRecordImpl<UnitwordsRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -740129700;

    /**
     * Setter for <code>UNITWORDS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>UNITWORDS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>UNITWORDS.TEXTBOOKID</code>.
     */
    public void setTextbookid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>UNITWORDS.TEXTBOOKID</code>.
     */
    public Integer getTextbookid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>UNITWORDS.UNIT</code>.
     */
    public void setUnit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>UNITWORDS.UNIT</code>.
     */
    public Integer getUnit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>UNITWORDS.PART</code>.
     */
    public void setPart(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>UNITWORDS.PART</code>.
     */
    public Integer getPart() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>UNITWORDS.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>UNITWORDS.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>UNITWORDS.WORD</code>.
     */
    public void setWord(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>UNITWORDS.WORD</code>.
     */
    public String getWord() {
        return (String) get(5);
    }

    /**
     * Setter for <code>UNITWORDS.NOTE</code>.
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>UNITWORDS.NOTE</code>.
     */
    public String getNote() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Unitwords.UNITWORDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Unitwords.UNITWORDS.TEXTBOOKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Unitwords.UNITWORDS.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Unitwords.UNITWORDS.PART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Unitwords.UNITWORDS.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Unitwords.UNITWORDS.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Unitwords.UNITWORDS.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTextbookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value2(Integer value) {
        setTextbookid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value3(Integer value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value4(Integer value) {
        setPart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value5(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value6(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord value7(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitwordsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitwordsRecord
     */
    public UnitwordsRecord() {
        super(Unitwords.UNITWORDS);
    }

    /**
     * Create a detached, initialised UnitwordsRecord
     */
    public UnitwordsRecord(Integer id, Integer textbookid, Integer unit, Integer part, Integer seqnum, String word, String note) {
        super(Unitwords.UNITWORDS);

        set(0, id);
        set(1, textbookid);
        set(2, unit);
        set(3, part);
        set(4, seqnum);
        set(5, word);
        set(6, note);
    }
}
