/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Usersettings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersettingsRecord extends UpdatableRecordImpl<UsersettingsRecord> implements Record9<Integer, Integer, Integer, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 86289836;

    /**
     * Setter for <code>USERSETTINGS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USERSETTINGS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USERSETTINGS.USERID</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>USERSETTINGS.USERID</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>USERSETTINGS.KIND</code>.
     */
    public void setKind(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>USERSETTINGS.KIND</code>.
     */
    public Integer getKind() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>USERSETTINGS.ENTITYID</code>.
     */
    public void setEntityid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>USERSETTINGS.ENTITYID</code>.
     */
    public Integer getEntityid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>USERSETTINGS.VALUE1</code>.
     */
    public void setValue1(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>USERSETTINGS.VALUE1</code>.
     */
    public String getValue1() {
        return (String) get(4);
    }

    /**
     * Setter for <code>USERSETTINGS.VALUE2</code>.
     */
    public void setValue2(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>USERSETTINGS.VALUE2</code>.
     */
    public String getValue2() {
        return (String) get(5);
    }

    /**
     * Setter for <code>USERSETTINGS.VALUE3</code>.
     */
    public void setValue3(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>USERSETTINGS.VALUE3</code>.
     */
    public String getValue3() {
        return (String) get(6);
    }

    /**
     * Setter for <code>USERSETTINGS.VALUE4</code>.
     */
    public void setValue4(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>USERSETTINGS.VALUE4</code>.
     */
    public String getValue4() {
        return (String) get(7);
    }

    /**
     * Setter for <code>USERSETTINGS.VALUE5</code>.
     */
    public void setValue5(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>USERSETTINGS.VALUE5</code>.
     */
    public String getValue5() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usersettings.USERSETTINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Usersettings.USERSETTINGS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Usersettings.USERSETTINGS.KIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Usersettings.USERSETTINGS.ENTITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Usersettings.USERSETTINGS.VALUE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Usersettings.USERSETTINGS.VALUE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Usersettings.USERSETTINGS.VALUE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Usersettings.USERSETTINGS.VALUE4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Usersettings.USERSETTINGS.VALUE5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getKind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getValue1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getValue2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getValue3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getValue4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getValue5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value3(Integer value) {
        setKind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value4(Integer value) {
        setEntityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value5(String value) {
        setValue1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value6(String value) {
        setValue2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value7(String value) {
        setValue3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value8(String value) {
        setValue4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord value9(String value) {
        setValue5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersettingsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersettingsRecord
     */
    public UsersettingsRecord() {
        super(Usersettings.USERSETTINGS);
    }

    /**
     * Create a detached, initialised UsersettingsRecord
     */
    public UsersettingsRecord(Integer id, Integer userid, Integer kind, Integer entityid, String value1, String value2, String value3, String value4, String value5) {
        super(Usersettings.USERSETTINGS);

        set(0, id);
        set(1, userid);
        set(2, kind);
        set(3, entityid);
        set(4, value1);
        set(5, value2);
        set(6, value3);
        set(7, value4);
        set(8, value5);
    }
}
