/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vdictionaries;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VdictionariesRecord extends TableRecordImpl<VdictionariesRecord> implements Record15<Integer, Integer, Integer, Integer, String, String, String, String, String, Object, String, String, String, Integer, String> {

    private static final long serialVersionUID = -887599054;

    /**
     * Setter for <code>VDICTIONARIES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VDICTIONARIES.LANGIDFROM</code>.
     */
    public void setLangidfrom(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.LANGIDFROM</code>.
     */
    public Integer getLangidfrom() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VDICTIONARIES.LANGIDTO</code>.
     */
    public void setLangidto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.LANGIDTO</code>.
     */
    public Integer getLangidto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VDICTIONARIES.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>VDICTIONARIES.DICTTYPENAME</code>.
     */
    public void setDicttypename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.DICTTYPENAME</code>.
     */
    public String getDicttypename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>VDICTIONARIES.DICTNAME</code>.
     */
    public void setDictname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.DICTNAME</code>.
     */
    public String getDictname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>VDICTIONARIES.URL</code>.
     */
    public void setUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.URL</code>.
     */
    public String getUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>VDICTIONARIES.CHCONV</code>.
     */
    public void setChconv(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.CHCONV</code>.
     */
    public String getChconv() {
        return (String) get(7);
    }

    /**
     * Setter for <code>VDICTIONARIES.AUTOMATION</code>.
     */
    public void setAutomation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.AUTOMATION</code>.
     */
    public String getAutomation() {
        return (String) get(8);
    }

    /**
     * Setter for <code>VDICTIONARIES.AUTOJUMP</code>.
     */
    public void setAutojump(Object value) {
        set(9, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.AUTOJUMP</code>.
     */
    public Object getAutojump() {
        return (Object) get(9);
    }

    /**
     * Setter for <code>VDICTIONARIES.DICTTABLE</code>.
     */
    public void setDicttable(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.DICTTABLE</code>.
     */
    public String getDicttable() {
        return (String) get(10);
    }

    /**
     * Setter for <code>VDICTIONARIES.TRANSFORM_WIN</code>.
     */
    public void setTransformWin(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.TRANSFORM_WIN</code>.
     */
    public String getTransformWin() {
        return (String) get(11);
    }

    /**
     * Setter for <code>VDICTIONARIES.TRANSFORM_MAC</code>.
     */
    public void setTransformMac(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.TRANSFORM_MAC</code>.
     */
    public String getTransformMac() {
        return (String) get(12);
    }

    /**
     * Setter for <code>VDICTIONARIES.WAIT</code>.
     */
    public void setWait(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.WAIT</code>.
     */
    public Integer getWait() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>VDICTIONARIES.TEMPLATE</code>.
     */
    public void setTemplate(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>VDICTIONARIES.TEMPLATE</code>.
     */
    public String getTemplate() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Integer, Integer, Integer, String, String, String, String, String, Object, String, String, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Integer, Integer, Integer, String, String, String, String, String, Object, String, String, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vdictionaries.VDICTIONARIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Vdictionaries.VDICTIONARIES.LANGIDFROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vdictionaries.VDICTIONARIES.LANGIDTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Vdictionaries.VDICTIONARIES.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Vdictionaries.VDICTIONARIES.DICTTYPENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Vdictionaries.VDICTIONARIES.DICTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Vdictionaries.VDICTIONARIES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Vdictionaries.VDICTIONARIES.CHCONV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Vdictionaries.VDICTIONARIES.AUTOMATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field10() {
        return Vdictionaries.VDICTIONARIES.AUTOJUMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Vdictionaries.VDICTIONARIES.DICTTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Vdictionaries.VDICTIONARIES.TRANSFORM_WIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Vdictionaries.VDICTIONARIES.TRANSFORM_MAC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Vdictionaries.VDICTIONARIES.WAIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Vdictionaries.VDICTIONARIES.TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangidfrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLangidto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDicttypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDictname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getChconv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAutomation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value10() {
        return getAutojump();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDicttable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTransformWin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTransformMac();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getWait();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value2(Integer value) {
        setLangidfrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value3(Integer value) {
        setLangidto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value4(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value5(String value) {
        setDicttypename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value6(String value) {
        setDictname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value7(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value8(String value) {
        setChconv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value9(String value) {
        setAutomation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value10(Object value) {
        setAutojump(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value11(String value) {
        setDicttable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value12(String value) {
        setTransformWin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value13(String value) {
        setTransformMac(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value14(Integer value) {
        setWait(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord value15(String value) {
        setTemplate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VdictionariesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9, Object value10, String value11, String value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VdictionariesRecord
     */
    public VdictionariesRecord() {
        super(Vdictionaries.VDICTIONARIES);
    }

    /**
     * Create a detached, initialised VdictionariesRecord
     */
    public VdictionariesRecord(Integer id, Integer langidfrom, Integer langidto, Integer seqnum, String dicttypename, String dictname, String url, String chconv, String automation, Object autojump, String dicttable, String transformWin, String transformMac, Integer wait, String template) {
        super(Vdictionaries.VDICTIONARIES);

        set(0, id);
        set(1, langidfrom);
        set(2, langidto);
        set(3, seqnum);
        set(4, dicttypename);
        set(5, dictname);
        set(6, url);
        set(7, chconv);
        set(8, automation);
        set(9, autojump);
        set(10, dicttable);
        set(11, transformWin);
        set(12, transformMac);
        set(13, wait);
        set(14, template);
    }
}
