/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vetextbooks;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetextbooksRecord extends TableRecordImpl<VetextbooksRecord> implements Record6<Integer, Integer, String, Integer, String, String> {

    private static final long serialVersionUID = 1190012643;

    /**
     * Setter for <code>VETEXTBOOKS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VETEXTBOOKS.LANGID</code>.
     */
    public void setLangid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.LANGID</code>.
     */
    public Integer getLangid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VETEXTBOOKS.ETEXTBOOKNAME</code>.
     */
    public void setEtextbookname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.ETEXTBOOKNAME</code>.
     */
    public String getEtextbookname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>VETEXTBOOKS.PAGES</code>.
     */
    public void setPages(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.PAGES</code>.
     */
    public Integer getPages() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>VETEXTBOOKS.USFILENAME</code>.
     */
    public void setUsfilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.USFILENAME</code>.
     */
    public String getUsfilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>VETEXTBOOKS.USPAGE</code>.
     */
    public void setUspage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>VETEXTBOOKS.USPAGE</code>.
     */
    public String getUspage() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vetextbooks.VETEXTBOOKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Vetextbooks.VETEXTBOOKS.LANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Vetextbooks.VETEXTBOOKS.ETEXTBOOKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Vetextbooks.VETEXTBOOKS.PAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Vetextbooks.VETEXTBOOKS.USFILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Vetextbooks.VETEXTBOOKS.USPAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEtextbookname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsfilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUspage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value2(Integer value) {
        setLangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value3(String value) {
        setEtextbookname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value4(Integer value) {
        setPages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value5(String value) {
        setUsfilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord value6(String value) {
        setUspage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VetextbooksRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VetextbooksRecord
     */
    public VetextbooksRecord() {
        super(Vetextbooks.VETEXTBOOKS);
    }

    /**
     * Create a detached, initialised VetextbooksRecord
     */
    public VetextbooksRecord(Integer id, Integer langid, String etextbookname, Integer pages, String usfilename, String uspage) {
        super(Vetextbooks.VETEXTBOOKS);

        set(0, id);
        set(1, langid);
        set(2, etextbookname);
        set(3, pages);
        set(4, usfilename);
        set(5, uspage);
    }
}
