/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vlanguages;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VlanguagesRecord extends TableRecordImpl<VlanguagesRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1217139304;

    /**
     * Setter for <code>VLANGUAGES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VLANGUAGES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VLANGUAGES.LANGNAME</code>.
     */
    public void setLangname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VLANGUAGES.LANGNAME</code>.
     */
    public String getLangname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VLANGUAGES.VOICE</code>.
     */
    public void setVoice(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VLANGUAGES.VOICE</code>.
     */
    public String getVoice() {
        return (String) get(2);
    }

    /**
     * Setter for <code>VLANGUAGES.USTEXTBOOKID</code>.
     */
    public void setUstextbookid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>VLANGUAGES.USTEXTBOOKID</code>.
     */
    public String getUstextbookid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>VLANGUAGES.USDICTID</code>.
     */
    public void setUsdictid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>VLANGUAGES.USDICTID</code>.
     */
    public String getUsdictid() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vlanguages.VLANGUAGES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Vlanguages.VLANGUAGES.LANGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Vlanguages.VLANGUAGES.VOICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vlanguages.VLANGUAGES.USTEXTBOOKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Vlanguages.VLANGUAGES.USDICTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLangname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVoice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUstextbookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsdictid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord value2(String value) {
        setLangname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord value3(String value) {
        setVoice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord value4(String value) {
        setUstextbookid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord value5(String value) {
        setUsdictid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VlanguagesRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VlanguagesRecord
     */
    public VlanguagesRecord() {
        super(Vlanguages.VLANGUAGES);
    }

    /**
     * Create a detached, initialised VlanguagesRecord
     */
    public VlanguagesRecord(Integer id, String langname, String voice, String ustextbookid, String usdictid) {
        super(Vlanguages.VLANGUAGES);

        set(0, id);
        set(1, langname);
        set(2, voice);
        set(3, ustextbookid);
        set(4, usdictid);
    }
}
