/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vtextsites;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VtextsitesRecord extends TableRecordImpl<VtextsitesRecord> implements Record8<Integer, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = -2131419348;

    /**
     * Setter for <code>VTEXTSITES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VTEXTSITES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VTEXTSITES.TEXTSITENAME</code>.
     */
    public void setTextsitename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VTEXTSITES.TEXTSITENAME</code>.
     */
    public String getTextsitename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VTEXTSITES.TRANSFORM_WIN</code>.
     */
    public void setTransformWin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VTEXTSITES.TRANSFORM_WIN</code>.
     */
    public String getTransformWin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>VTEXTSITES.TRANSFORM_MAC</code>.
     */
    public void setTransformMac(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>VTEXTSITES.TRANSFORM_MAC</code>.
     */
    public String getTransformMac() {
        return (String) get(3);
    }

    /**
     * Setter for <code>VTEXTSITES.TEMPLATE</code>.
     */
    public void setTemplate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>VTEXTSITES.TEMPLATE</code>.
     */
    public String getTemplate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>VTEXTSITES.URL</code>.
     */
    public void setUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>VTEXTSITES.URL</code>.
     */
    public String getUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>VTEXTSITES.USFOLDER</code>.
     */
    public void setUsfolder(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>VTEXTSITES.USFOLDER</code>.
     */
    public String getUsfolder() {
        return (String) get(6);
    }

    /**
     * Setter for <code>VTEXTSITES.WAIT</code>.
     */
    public void setWait(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>VTEXTSITES.WAIT</code>.
     */
    public Integer getWait() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vtextsites.VTEXTSITES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Vtextsites.VTEXTSITES.TEXTSITENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Vtextsites.VTEXTSITES.TRANSFORM_WIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vtextsites.VTEXTSITES.TRANSFORM_MAC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Vtextsites.VTEXTSITES.TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Vtextsites.VTEXTSITES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Vtextsites.VTEXTSITES.USFOLDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Vtextsites.VTEXTSITES.WAIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTextsitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTransformWin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTransformMac();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUsfolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getWait();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value2(String value) {
        setTextsitename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value3(String value) {
        setTransformWin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value4(String value) {
        setTransformMac(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value5(String value) {
        setTemplate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value6(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value7(String value) {
        setUsfolder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord value8(Integer value) {
        setWait(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VtextsitesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VtextsitesRecord
     */
    public VtextsitesRecord() {
        super(Vtextsites.VTEXTSITES);
    }

    /**
     * Create a detached, initialised VtextsitesRecord
     */
    public VtextsitesRecord(Integer id, String textsitename, String transformWin, String transformMac, String template, String url, String usfolder, Integer wait) {
        super(Vtextsites.VTEXTSITES);

        set(0, id);
        set(1, textsitename);
        set(2, transformWin);
        set(3, transformMac);
        set(4, template);
        set(5, url);
        set(6, usfolder);
        set(7, wait);
    }
}
