/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vunitphrases;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VunitphrasesRecord extends TableRecordImpl<VunitphrasesRecord> implements Record8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1224889861;

    /**
     * Setter for <code>VUNITPHRASES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VUNITPHRASES.TEXTBOOKID</code>.
     */
    public void setTextbookid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.TEXTBOOKID</code>.
     */
    public Integer getTextbookid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VUNITPHRASES.UNIT</code>.
     */
    public void setUnit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.UNIT</code>.
     */
    public Integer getUnit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VUNITPHRASES.PART</code>.
     */
    public void setPart(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.PART</code>.
     */
    public Integer getPart() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>VUNITPHRASES.SEQNUM</code>.
     */
    public void setSeqnum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.SEQNUM</code>.
     */
    public Integer getSeqnum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>VUNITPHRASES.LANGPHRASEID</code>.
     */
    public void setLangphraseid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.LANGPHRASEID</code>.
     */
    public Integer getLangphraseid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>VUNITPHRASES.PHRASE</code>.
     */
    public void setPhrase(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.PHRASE</code>.
     */
    public String getPhrase() {
        return (String) get(6);
    }

    /**
     * Setter for <code>VUNITPHRASES.TRANSLATION</code>.
     */
    public void setTranslation(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>VUNITPHRASES.TRANSLATION</code>.
     */
    public String getTranslation() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vunitphrases.VUNITPHRASES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Vunitphrases.VUNITPHRASES.TEXTBOOKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vunitphrases.VUNITPHRASES.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Vunitphrases.VUNITPHRASES.PART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Vunitphrases.VUNITPHRASES.SEQNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Vunitphrases.VUNITPHRASES.LANGPHRASEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Vunitphrases.VUNITPHRASES.PHRASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Vunitphrases.VUNITPHRASES.TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTextbookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSeqnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLangphraseid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhrase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value2(Integer value) {
        setTextbookid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value3(Integer value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value4(Integer value) {
        setPart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value5(Integer value) {
        setSeqnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value6(Integer value) {
        setLangphraseid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value7(String value) {
        setPhrase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord value8(String value) {
        setTranslation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VunitphrasesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VunitphrasesRecord
     */
    public VunitphrasesRecord() {
        super(Vunitphrases.VUNITPHRASES);
    }

    /**
     * Create a detached, initialised VunitphrasesRecord
     */
    public VunitphrasesRecord(Integer id, Integer textbookid, Integer unit, Integer part, Integer seqnum, Integer langphraseid, String phrase, String translation) {
        super(Vunitphrases.VUNITPHRASES);

        set(0, id);
        set(1, textbookid);
        set(2, unit);
        set(3, part);
        set(4, seqnum);
        set(5, langphraseid);
        set(6, phrase);
        set(7, translation);
    }
}
