/**
 * This class is generated by jOOQ
 */
package com.zwstudio.lolly.jooq.tables.records;


import com.zwstudio.lolly.jooq.tables.Vusersettings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VusersettingsRecord extends TableRecordImpl<VusersettingsRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 124817820;

    /**
     * Setter for <code>VUSERSETTINGS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VUSERSETTINGS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VUSERSETTINGS.USERID</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VUSERSETTINGS.USERID</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VUSERSETTINGS.ENTITYID</code>.
     */
    public void setEntityid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VUSERSETTINGS.ENTITYID</code>.
     */
    public Integer getEntityid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VUSERSETTINGS.USLANGID</code>.
     */
    public void setUslangid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>VUSERSETTINGS.USLANGID</code>.
     */
    public String getUslangid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vusersettings.VUSERSETTINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Vusersettings.VUSERSETTINGS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vusersettings.VUSERSETTINGS.ENTITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vusersettings.VUSERSETTINGS.USLANGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEntityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUslangid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VusersettingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VusersettingsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VusersettingsRecord value3(Integer value) {
        setEntityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VusersettingsRecord value4(String value) {
        setUslangid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VusersettingsRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VusersettingsRecord
     */
    public VusersettingsRecord() {
        super(Vusersettings.VUSERSETTINGS);
    }

    /**
     * Create a detached, initialised VusersettingsRecord
     */
    public VusersettingsRecord(Integer id, Integer userid, Integer entityid, String uslangid) {
        super(Vusersettings.VUSERSETTINGS);

        set(0, id);
        set(1, userid);
        set(2, entityid);
        set(3, uslangid);
    }
}
