package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "BOOKS")
public class Book implements java.io.Serializable {

	private int bookid;
	private int langid;
	private String bookname;
	private int unitsinbook;
	private String parts;
	private int unitfrom;
	private int partfrom;
	private int unitto;
	private int partto;

	public Book() {
	}

	public Book(int bookid, int langid, String bookname, int unitsinbook,
			String parts, int unitfrom, int partfrom, int unitto, int partto) {
		this.bookid = bookid;
		this.langid = langid;
		this.bookname = bookname;
		this.unitsinbook = unitsinbook;
		this.parts = parts;
		this.unitfrom = unitfrom;
		this.partfrom = partfrom;
		this.unitto = unitto;
		this.partto = partto;
	}

	@Id
	@Column(name = "BOOKID", nullable = false)
	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	@Column(name = "LANGID", nullable = false)
	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	@Column(name = "BOOKNAME", nullable = false, length = 2000000000)
	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	@Column(name = "UNITSINBOOK", nullable = false)
	public int getUnitsinbook() {
		return this.unitsinbook;
	}

	public void setUnitsinbook(int unitsinbook) {
		this.unitsinbook = unitsinbook;
	}

	@Column(name = "PARTS", nullable = false, length = 2000000000)
	public String getParts() {
		return this.parts;
	}

	public void setParts(String parts) {
		this.parts = parts;
	}

	@Column(name = "UNITFROM", nullable = false)
	public int getUnitfrom() {
		return this.unitfrom;
	}

	public void setUnitfrom(int unitfrom) {
		this.unitfrom = unitfrom;
	}

	@Column(name = "PARTFROM", nullable = false)
	public int getPartfrom() {
		return this.partfrom;
	}

	public void setPartfrom(int partfrom) {
		this.partfrom = partfrom;
	}

	@Column(name = "UNITTO", nullable = false)
	public int getUnitto() {
		return this.unitto;
	}

	public void setUnitto(int unitto) {
		this.unitto = unitto;
	}

	@Column(name = "PARTTO", nullable = false)
	public int getPartto() {
		return this.partto;
	}

	public void setPartto(int partto) {
		this.partto = partto;
	}

}
