package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:56:03 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DictAllId generated by hbm2java
 */
@Embeddable
public class DictAllId implements java.io.Serializable {

	private Integer langid;
	private String dictname;

	public DictAllId() {
	}

	public DictAllId(Integer langid, String dictname) {
		this.langid = langid;
		this.dictname = dictname;
	}

	@Column(name = "LANGID")
	public Integer getLangid() {
		return this.langid;
	}

	public void setLangid(Integer langid) {
		this.langid = langid;
	}

	@Column(name = "DICTNAME", length = 2000000000)
	public String getDictname() {
		return this.dictname;
	}

	public void setDictname(String dictname) {
		this.dictname = dictname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DictAllId))
			return false;
		DictAllId castOther = (DictAllId) other;

		return ((this.getLangid() == castOther.getLangid()) || (this
				.getLangid() != null && castOther.getLangid() != null && this
				.getLangid().equals(castOther.getLangid())))
				&& ((this.getDictname() == castOther.getDictname()) || (this
						.getDictname() != null
						&& castOther.getDictname() != null && this
						.getDictname().equals(castOther.getDictname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLangid() == null ? 0 : this.getLangid().hashCode());
		result = 37 * result
				+ (getDictname() == null ? 0 : this.getDictname().hashCode());
		return result;
	}

}
