package com.zwstudio.lolly.domain;
// Generated 2016/08/06 9:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DictionaryId generated by hbm2java
 */
@Embeddable
public class DictionaryId implements java.io.Serializable {

	private int langidfrom;
	private String dictname;

	public DictionaryId() {
	}

	public DictionaryId(int langidfrom, String dictname) {
		this.langidfrom = langidfrom;
		this.dictname = dictname;
	}

	@Column(name = "LANGIDFROM", nullable = false)
	public int getLangidfrom() {
		return this.langidfrom;
	}

	public void setLangidfrom(int langidfrom) {
		this.langidfrom = langidfrom;
	}

	@Column(name = "DICTNAME", nullable = false, length = 2000000000)
	public String getDictname() {
		return this.dictname;
	}

	public void setDictname(String dictname) {
		this.dictname = dictname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DictionaryId))
			return false;
		DictionaryId castOther = (DictionaryId) other;

		return (this.getLangidfrom() == castOther.getLangidfrom())
				&& ((this.getDictname() == castOther.getDictname()) || (this.getDictname() != null
						&& castOther.getDictname() != null && this.getDictname().equals(castOther.getDictname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLangidfrom();
		result = 37 * result + (getDictname() == null ? 0 : this.getDictname().hashCode());
		return result;
	}

}
