package com.zwstudio.lolly.domain;
// Generated 2016/08/06 9:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "VLANGUAGES2")
public class Language implements java.io.Serializable {

	private int langid;
	private String langname;
	private String voice;
	private String ustextbookid;

	public Language() {
	}

	public Language(int langid) {
		this.langid = langid;
	}

	public Language(int langid, String langname, String voice, String ustextbookid) {
		this.langid = langid;
		this.langname = langname;
		this.voice = voice;
		this.ustextbookid = ustextbookid;
	}

	@Id

	@Column(name = "LANGID", nullable = false)
	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	@Column(name = "LANGNAME", length = 2000000000)
	public String getLangname() {
		return this.langname;
	}

	public void setLangname(String langname) {
		this.langname = langname;
	}

	@Column(name = "VOICE", length = 2000000000)
	public String getVoice() {
		return this.voice;
	}

	public void setVoice(String voice) {
		this.voice = voice;
	}

	@Column(name = "USTEXTBOOKID", length = 2000000000)
	public String getUstextbookid() {
		return this.ustextbookid;
	}

	public void setUstextbookid(String ustextbookid) {
		this.ustextbookid = ustextbookid;
	}

}
