package com.zwstudio.lolly.domain;
// Generated 2016/08/18 14:00:46 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "VLANGUAGES")
public class Language implements java.io.Serializable {

	private int id;
	private String langname;
	private String voice;
	private Integer ustextbookid;
	private Integer usdictid;

	public Language() {
	}

	public Language(int id) {
		this.id = id;
	}

	public Language(int id, String langname, String voice, Integer ustextbookid, Integer usdictid) {
		this.id = id;
		this.langname = langname;
		this.voice = voice;
		this.ustextbookid = ustextbookid;
		this.usdictid = usdictid;
	}

	@Id

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LANGNAME", length = 2000000000)
	public String getLangname() {
		return this.langname;
	}

	public void setLangname(String langname) {
		this.langname = langname;
	}

	@Column(name = "VOICE", length = 2000000000)
	public String getVoice() {
		return this.voice;
	}

	public void setVoice(String voice) {
		this.voice = voice;
	}

	@Column(name = "USTEXTBOOKID")
	public Integer getUstextbookid() {
		return this.ustextbookid;
	}

	public void setUstextbookid(Integer ustextbookid) {
		this.ustextbookid = ustextbookid;
	}

	@Column(name = "USDICTID")
	public Integer getUsdictid() {
		return this.usdictid;
	}

	public void setUsdictid(Integer usdictid) {
		this.usdictid = usdictid;
	}

}
