package com.zwstudio.lolly.domain;
// Generated 2016/08/18 14:00:46 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LangPhrase generated by hbm2java
 */
@Entity
@Table(name = "LANGPHRASES")
public class LangPhrase implements java.io.Serializable {

	private int id;
	private int langid;
	private String phrase;
	private String translation;

	public LangPhrase() {
	}

	public LangPhrase(int id, int langid, String phrase) {
		this.id = id;
		this.langid = langid;
		this.phrase = phrase;
	}

	public LangPhrase(int id, int langid, String phrase, String translation) {
		this.id = id;
		this.langid = langid;
		this.phrase = phrase;
		this.translation = translation;
	}

	@Id

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LANGID", nullable = false)
	public int getLangid() {
		return this.langid;
	}

	public void setLangid(int langid) {
		this.langid = langid;
	}

	@Column(name = "PHRASE", nullable = false, length = 2000000000)
	public String getPhrase() {
		return this.phrase;
	}

	public void setPhrase(String phrase) {
		this.phrase = phrase;
	}

	@Column(name = "TRANSLATION", length = 2000000000)
	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

}
