package com.zwstudio.lolly.domain;
// Generated 2016/08/09 13:08:27 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TBWord generated by hbm2java
 */
@Entity
@Table(name = "VTBWORDS")
public class TBWord implements java.io.Serializable {

	private int id;
	private Integer langid;
	private String textbookname;
	private Integer unit;
	private Integer part;
	private Integer seqnum;
	private String word;
	private String note;

	public TBWord() {
	}

	public TBWord(int id) {
		this.id = id;
	}

	public TBWord(int id, Integer langid, String textbookname, Integer unit, Integer part, Integer seqnum, String word,
			String note) {
		this.id = id;
		this.langid = langid;
		this.textbookname = textbookname;
		this.unit = unit;
		this.part = part;
		this.seqnum = seqnum;
		this.word = word;
		this.note = note;
	}

	@Id

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LANGID")
	public Integer getLangid() {
		return this.langid;
	}

	public void setLangid(Integer langid) {
		this.langid = langid;
	}

	@Column(name = "TEXTBOOKNAME", length = 2000000000)
	public String getTextbookname() {
		return this.textbookname;
	}

	public void setTextbookname(String textbookname) {
		this.textbookname = textbookname;
	}

	@Column(name = "UNIT")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "PART")
	public Integer getPart() {
		return this.part;
	}

	public void setPart(Integer part) {
		this.part = part;
	}

	@Column(name = "SEQNUM")
	public Integer getSeqnum() {
		return this.seqnum;
	}

	public void setSeqnum(Integer seqnum) {
		this.seqnum = seqnum;
	}

	@Column(name = "WORD", length = 2000000000)
	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	@Column(name = "NOTE", length = 2000000000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
