package com.zwstudio.lolly.domain;
// Generated 2016/08/18 14:00:46 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnitPhrase generated by hbm2java
 */
@Entity
@Table(name = "VUNITPHRASES")
public class UnitPhrase implements java.io.Serializable {

	private int id;
	private Integer textbookid;
	private Integer unit;
	private Integer part;
	private Integer seqnum;
	private Integer langphraseid;
	private String phrase;
	private String translation;

	public UnitPhrase() {
	}

	public UnitPhrase(int id) {
		this.id = id;
	}

	public UnitPhrase(int id, Integer textbookid, Integer unit, Integer part, Integer seqnum, Integer langphraseid,
			String phrase, String translation) {
		this.id = id;
		this.textbookid = textbookid;
		this.unit = unit;
		this.part = part;
		this.seqnum = seqnum;
		this.langphraseid = langphraseid;
		this.phrase = phrase;
		this.translation = translation;
	}

	@Id

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TEXTBOOKID")
	public Integer getTextbookid() {
		return this.textbookid;
	}

	public void setTextbookid(Integer textbookid) {
		this.textbookid = textbookid;
	}

	@Column(name = "UNIT")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "PART")
	public Integer getPart() {
		return this.part;
	}

	public void setPart(Integer part) {
		this.part = part;
	}

	@Column(name = "SEQNUM")
	public Integer getSeqnum() {
		return this.seqnum;
	}

	public void setSeqnum(Integer seqnum) {
		this.seqnum = seqnum;
	}

	@Column(name = "LANGPHRASEID")
	public Integer getLangphraseid() {
		return this.langphraseid;
	}

	public void setLangphraseid(Integer langphraseid) {
		this.langphraseid = langphraseid;
	}

	@Column(name = "PHRASE", length = 2000000000)
	public String getPhrase() {
		return this.phrase;
	}

	public void setPhrase(String phrase) {
		this.phrase = phrase;
	}

	@Column(name = "TRANSLATION", length = 2000000000)
	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

}
