package com.zwstudio.lolly.domain;
// Generated 2016/08/18 14:00:46 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserSettings generated by hbm2java
 */
@Entity
@Table(name = "VUSERSETTINGS")
public class UserSetting implements java.io.Serializable {

	private int id;
	private Integer userid;
	private Integer entityid;
	private Integer uslangid;

	public UserSetting() {
	}

	public UserSetting(int id) {
		this.id = id;
	}

	public UserSetting(int id, Integer userid, Integer entityid, Integer uslangid) {
		this.id = id;
		this.userid = userid;
		this.entityid = entityid;
		this.uslangid = uslangid;
	}

	@Id

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "USERID")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "ENTITYID")
	public Integer getEntityid() {
		return this.entityid;
	}

	public void setEntityid(Integer entityid) {
		this.entityid = entityid;
	}

	@Column(name = "USLANGID")
	public Integer getUslangid() {
		return this.uslangid;
	}

	public void setUslangid(Integer uslangid) {
		this.uslangid = uslangid;
	}

}
